// src/views/poo/Heritage.vue
<template>
	<div>
		<h1>L'héritage</h1>
		<p>L'héritage est une notion de POO, elle permet de définir une classe comme enfant d'une autre classe. C'est-à-dire que la classe enfant va reprendre toutes les méthodes et tous les attributs de la classe parent. Le programmeur peut quand même y ajouter ses propres méthodes et attributs.</p>
		<p>Pour faire hériter une classe d'une autre classe, on utilise le mot réservé extends. Il s'utilise comme ceci dans la déclaration de la classe :</p>
		<pre class="language-java"><ShowCode file="poo/heritage0.java" lang="java"/></pre>
		<p>Les classes enfants ont les propriétés suivantes :</p>
		<ul>
			<li>Elles reprennent tous les attributs et méthodes de la classe parent.</li>
			<li>Si on y déclare une méthode avec le même nom que la classe parent, celle de la classe parent sera ignoré et remplacé par celle de la classe enfant.</li>
		</ul>
		<p>Voici un exemple d'une classe qui hérite d'une autre :</p>
		La classe parent : Personne
		<pre class="language-java"><ShowCode file="poo/heritage1.java" lang="java"/></pre>
		La classe enfant : Apprenti
		<pre class="language-java"><ShowCode file="poo/heritage2.java" lang="java"/></pre>
		<p>Ici, la classe Apprenti hérite de Personne. Ce qui veut dire qu'elle peut être utilisé exactement comme la classe Personne mais avec l'attribut formation en plus.</p>
	</div>
</template>

<script>
	import ShowCode from '../../components/ShowCode.vue'

	export default {
		name: 'Heritage',
		components: {
			ShowCode,
		},
	}
</script>

// angular/epsic-burkhalter-dev/src/app/poo-module/components/heritage/heritage.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";
import 'prismjs/components/prism-java';

declare var Prism: any;

@Component({
  selector: 'app-heritage',
  templateUrl: './heritage.component.html',
  styleUrls: ['./heritage.component.css']
})
export class HeritageComponent implements OnInit {

  public Prism: any = {};

  constructor(private _titleService: Title) {
    this._titleService.setTitle("L'héritage");
    this.Prism = Prism;
  }

  ngOnInit(): void {
  }

}

<h1>L'héritage</h1>
<p>L'héritage est une notion de POO, elle permet de définir une classe comme enfant d'une autre classe. C'est-à-dire que la classe enfant va reprendre toutes les méthodes et tous les attributs de la classe parent. Le programmeur peut quand même y ajouter ses propres méthodes et attributs.</p>
<p>Pour faire hériter une classe d'une autre classe, on utilise le mot réservé extends. Il s'utilise comme ceci dans la déclaration de la classe :</p>
<pre class="language-java"><app-code file="poo/heritage0.java" [lang]="Prism.languages.java"></app-code></pre>
<p>Les classes enfants ont les propriétés suivantes :</p>
<ul>
	<li>Elles reprennent tous les attributs et méthodes de la classe parent.</li>
	<li>Si on y déclare une méthode avec le même nom que la classe parent, celle de la classe parent sera ignoré et remplacé par celle de la classe enfant.</li>
</ul>
<p>Voici un exemple d'une classe qui hérite d'une autre :</p>
La classe parent : Personne
<pre class="language-java"><app-code file="poo/heritage1.java" [lang]="Prism.languages.java"></app-code></pre>
La classe enfant : Apprenti
<pre class="language-java"><app-code file="poo/heritage2.java" [lang]="Prism.languages.java"></app-code></pre>
<p>Ici, la classe Apprenti hérite de Personne. Ce qui veut dire qu'elle peut être utilisé exactement comme la classe Personne mais avec l'attribut formation en plus.</p>
