// src/app/java-module/components/conditions-avancees/conditions-avancees.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";
import 'prismjs/components/prism-java';

declare var Prism: any;

@Component({
  selector: 'app-conditions-avancees',
  templateUrl: './conditions-avancees.component.html',
  styleUrls: ['./conditions-avancees.component.css']
})
export class ConditionsAvanceesComponent implements OnInit {

  public Prism: any = {};

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Les conditions avancées");
    this.Prism = Prism;
  }

  ngOnInit(): void {
  }

}

<h1>Les conditions avancées</h1>

<h3>Le switch</h3>
<p>Le bloc switch permet de simplifier un code où on utiliserait plusieurs else if à la suite. Exemple :</p>
<table class="table">
	<thead>
		<tr>
			<th>If else if</th>
			<th>Switch</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<pre class="language-java"><app-code file="java/if-else-if-else.java" [lang]="Prism.languages.java"></app-code></pre>
			</td>
			<td>
				<pre class="language-java"><app-code file="java/switch.java" [lang]="Prism.languages.java"></app-code></pre>
			</td>
		</tr>
	</tbody>
</table>
<p>Le break est très important : il sert à sortir du switch si la condition est remplie. Si vous l'oubliez alors votre switch exécutera la condition plus toutes celles qui se trouve après.</p>

// src/modules/java/views/ConditionsAvancees.vue
<script setup>
import ShowCode from "@/components/ShowCode.vue"
</script>

<template>
  <div>
    <h2>Le switch</h2>
    <p>
      Le bloc <code>switch</code> permet de simplifier un code où on utiliserait
      plusieurs <code>else if</code> à la suite. Exemple :
    </p>
    <table>
      <thead>
        <tr>
          <th>If else if ...</th>
          <th>Switch</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <ShowCode file="/java/code/if-else-if-else.java" lang="java" />
          </td>
          <td>
            <ShowCode file="/java/code/switch.java" lang="java" />
          </td>
        </tr>
      </tbody>
    </table>
    <p>
      Le <code>break</code> est très important. Il sert à sortir du
      <code>switch</code> si la condition est remplie. Si vous l'oubliez, alors
      votre <code>switch</code> exécutera également le code des conditions se
      trouvant après.
    </p>
  </div>
</template>

<style scoped>
td {
  @apply align-top;
}
</style>
