// src/views/bin/Ascii.vue
<template>
	<div>
		<h1>Code ASCII</h1>
		<p>L'acronyme ASCII signifie American Standard Code for Information Interchange (Code américain normalisé pour l'échange d'information).</p>
		<ul>
			<li>L'ASCII se code sur 7 bits, soit 128 caractères.</li>
			<li>L'ASCII étendu se code sur 8 bits, soit 256 caractères.</li>
		</ul>

		<h3>Table ASCII</h3>
		<p>Les 32 premiers caractères (0 à 31) et le dernier (127) ne sont pas directement utilisables, ils étaient utilisé par la machines pour différentes choses</p>
		<div class="row">
			<div class="col-xs-3">
				<table style="text-align: center; border: 1px solid black;" cellpadding="0">
					<tr><th>Décimale&nbsp;</th><th>Hexadécimale&nbsp;</th><th>ASCII&nbsp;</th></tr>
					<tr><td>0</td><td>0</td><td><i>NUL</i></td></tr>
					<tr><td>1</td><td>1</td><td><i>SOH</i></td></tr>
					<tr><td>2</td><td>2</td><td><i>STX</i></td></tr>
					<tr><td>3</td><td>3</td><td><i>ETX</i></td></tr>
					<tr><td>4</td><td>4</td><td><i>EOT</i></td></tr>
					<tr><td>5</td><td>5</td><td><i>ENQ</i></td></tr>
					<tr><td>6</td><td>6</td><td><i>ACK</i></td></tr>
					<tr><td>7</td><td>7</td><td><i>BEL</i></td></tr>
					<tr><td>8</td><td>8</td><td><i>BS</i></td></tr>
					<tr><td>9</td><td>9</td><td><i>HT</i></td></tr>
					<tr><td>10</td><td>0A</td><td><i>LF</i></td></tr>
					<tr><td>11</td><td>0B</td><td><i>VT</i></td></tr>
					<tr><td>12</td><td>0C</td><td><i>FF</i></td></tr>
					<tr><td>13</td><td>0D</td><td><i>CR</i></td></tr>
					<tr><td>14</td><td>0E</td><td><i>SO</i></td></tr>
					<tr><td>15</td><td>0F</td><td><i>SI</i></td></tr>
					<tr><td>16</td><td>10</td><td><i>DLE</i></td></tr>
					<tr><td>17</td><td>11</td><td><i>DC1</i></td></tr>
					<tr><td>18</td><td>12</td><td><i>DC2</i></td></tr>
					<tr><td>19</td><td>13</td><td><i>DC3</i></td></tr>
					<tr><td>20</td><td>14</td><td><i>DC4</i></td></tr>
					<tr><td>21</td><td>15</td><td><i>NAK</i></td></tr>
					<tr><td>22</td><td>16</td><td><i>SYN</i></td></tr>
					<tr><td>23</td><td>17</td><td><i>ETB</i></td></tr>
					<tr><td>24</td><td>18</td><td><i>CAN</i></td></tr>
					<tr><td>25</td><td>19</td><td><i>EM</i></td></tr>
					<tr><td>26</td><td>1A</td><td><i>SUB</i></td></tr>
					<tr><td>27</td><td>1B</td><td><i>ESC</i></td></tr>
					<tr><td>28</td><td>1C</td><td><i>FS</i></td></tr>
					<tr><td>29</td><td>1D</td><td><i>GS</i></td></tr>
					<tr><td>30</td><td>1E</td><td><i>RS</i></td></tr>
					<tr><td>31</td><td>1F</td><td><i>US</i></td></tr>
				</table>
			</div>
			<div class="col-xs-3">
				<table style="text-align: center; border: 1px solid black" cellpadding="0">
					<tr><th>Décimale&nbsp;</th><th>Hexadécimale&nbsp;</th><th>ASCII&nbsp;</th></tr>
					<tr><td>32</td><td>20</td><td>SP (Space)</td></tr>
					<tr><td>33</td><td>21</td><td>!</td></tr>
					<tr><td>34</td><td>22</td><td>"</td></tr>
					<tr><td>35</td><td>23</td><td>#</td></tr>
					<tr><td>36</td><td>24</td><td>$</td></tr>
					<tr><td>37</td><td>25</td><td>%</td></tr>
					<tr><td>38</td><td>26</td><td>&</td></tr>
					<tr><td>39</td><td>27</td><td>'</td></tr>
					<tr><td>40</td><td>28</td><td>(</td></tr>
					<tr><td>41</td><td>29</td><td>)</td></tr>
					<tr><td>42</td><td>2A</td><td>*</td></tr>
					<tr><td>43</td><td>2B</td><td>+</td></tr>
					<tr><td>44</td><td>2C</td><td>,</td></tr>
					<tr><td>45</td><td>2D</td><td>-</td></tr>
					<tr><td>46</td><td>2E</td><td>.</td></tr>
					<tr><td>47</td><td>2F</td><td>/</td></tr>
					<tr><td>48</td><td>30</td><td>0</td></tr>
					<tr><td>49</td><td>31</td><td>1</td></tr>
					<tr><td>50</td><td>32</td><td>2</td></tr>
					<tr><td>51</td><td>33</td><td>3</td></tr>
					<tr><td>52</td><td>34</td><td>4</td></tr>
					<tr><td>53</td><td>35</td><td>5</td></tr>
					<tr><td>54</td><td>36</td><td>6</td></tr>
					<tr><td>55</td><td>37</td><td>7</td></tr>
					<tr><td>56</td><td>38</td><td>8</td></tr>
					<tr><td>57</td><td>39</td><td>9</td></tr>
					<tr><td>58</td><td>3A</td><td>:</td></tr>
					<tr><td>59</td><td>3B</td><td>;</td></tr>
					<tr><td>60</td><td>3C</td><td>&lt;</td></tr>
					<tr><td>61</td><td>3D</td><td>=</td></tr>
					<tr><td>62</td><td>3E</td><td>&gt;</td></tr>
					<tr><td>63</td><td>3F</td><td>?</td></tr>
				</table>
			</div>
			<div class="col-xs-3">
				<table style="text-align: center; border: 1px solid black" cellpadding="0">
					<tr><th>Décimale&nbsp;</th><th>Hexadécimale&nbsp;</th><th>ASCII&nbsp;</th></tr>
					<tr><td>64</td><td>40</td><td>@</td></tr>
					<tr><td>65</td><td>41</td><td>A</td></tr>
					<tr><td>66</td><td>42</td><td>B</td></tr>
					<tr><td>67</td><td>43</td><td>C</td></tr>
					<tr><td>68</td><td>44</td><td>D</td></tr>
					<tr><td>69</td><td>45</td><td>E</td></tr>
					<tr><td>70</td><td>46</td><td>F</td></tr>
					<tr><td>71</td><td>47</td><td>G</td></tr>
					<tr><td>72</td><td>48</td><td>H</td></tr>
					<tr><td>73</td><td>49</td><td>I</td></tr>
					<tr><td>74</td><td>4A</td><td>J</td></tr>
					<tr><td>75</td><td>4B</td><td>K</td></tr>
					<tr><td>76</td><td>4C</td><td>L</td></tr>
					<tr><td>77</td><td>4D</td><td>M</td></tr>
					<tr><td>78</td><td>4E</td><td>N</td></tr>
					<tr><td>79</td><td>4F</td><td>O</td></tr>
					<tr><td>80</td><td>50</td><td>P</td></tr>
					<tr><td>81</td><td>51</td><td>Q</td></tr>
					<tr><td>82</td><td>52</td><td>R</td></tr>
					<tr><td>83</td><td>53</td><td>S</td></tr>
					<tr><td>84</td><td>54</td><td>T</td></tr>
					<tr><td>85</td><td>55</td><td>U</td></tr>
					<tr><td>86</td><td>56</td><td>V</td></tr>
					<tr><td>87</td><td>57</td><td>W</td></tr>
					<tr><td>88</td><td>58</td><td>X</td></tr>
					<tr><td>89</td><td>59</td><td>Y</td></tr>
					<tr><td>90</td><td>5A</td><td>Z</td></tr>
					<tr><td>91</td><td>5B</td><td>[</td></tr>
					<tr><td>92</td><td>5C</td><td>\</td></tr>
					<tr><td>93</td><td>5D</td><td>]</td></tr>
					<tr><td>94</td><td>5E</td><td>^</td></tr>
					<tr><td>95</td><td>5F</td><td>_</td></tr>
				</table>
			</div>
			<div class="col-xs-3">
				<table style="text-align: center; border: 1px solid black" cellpadding="0">
					<tr><th>Décimale&nbsp;</th><th>Hexadécimale&nbsp;</th><th>ASCII&nbsp;</th></tr>
					<tr><td>96</td><td>60</td><td>`</td></tr>
					<tr><td>97</td><td>61</td><td>a</td></tr>
					<tr><td>98</td><td>62</td><td>b</td></tr>
					<tr><td>99</td><td>63</td><td>c</td></tr>
					<tr><td>100</td><td>64</td><td>d</td></tr>
					<tr><td>101</td><td>65</td><td>e</td></tr>
					<tr><td>102</td><td>66</td><td>f</td></tr>
					<tr><td>103</td><td>67</td><td>g</td></tr>
					<tr><td>104</td><td>68</td><td>h</td></tr>
					<tr><td>105</td><td>69</td><td>i</td></tr>
					<tr><td>106</td><td>6A</td><td>j</td></tr>
					<tr><td>107</td><td>6B</td><td>k</td></tr>
					<tr><td>108</td><td>6C</td><td>l</td></tr>
					<tr><td>109</td><td>6D</td><td>m</td></tr>
					<tr><td>110</td><td>6E</td><td>n</td></tr>
					<tr><td>111</td><td>6F</td><td>o</td></tr>
					<tr><td>112</td><td>70</td><td>p</td></tr>
					<tr><td>113</td><td>71</td><td>q</td></tr>
					<tr><td>114</td><td>72</td><td>r</td></tr>
					<tr><td>115</td><td>73</td><td>s</td></tr>
					<tr><td>116</td><td>74</td><td>t</td></tr>
					<tr><td>117</td><td>75</td><td>u</td></tr>
					<tr><td>118</td><td>76</td><td>v</td></tr>
					<tr><td>119</td><td>77</td><td>w</td></tr>
					<tr><td>120</td><td>78</td><td>x</td></tr>
					<tr><td>121</td><td>79</td><td>y</td></tr>
					<tr><td>122</td><td>7A</td><td>z</td></tr>
					<tr><td>123</td><td>7B</td><td>&lcub;</td></tr>
					<tr><td>124</td><td>7C</td><td>|</td></tr>
					<tr><td>125</td><td>7D</td><td>}</td></tr>
					<tr><td>126</td><td>7E</td><td>~</td></tr>
					<tr><td>127</td><td>7F</td><td><i>DEL</i></td></tr>
				</table>
			</div>
		</div>
		<br>

		<h3>ASCII étendu</h3>
		<p>Le code ASCII étendu utilise 8 bits (au lieu de 7 pour l'ASCII). Il n'est cependant pas normalisé. Il est donc possible de voir des tables différentes de celle-ci :</p>
		<img src="/medias/bin/extended_ascii.jpg" alt="Table ASCII étendu" />
	</div>
</template>

<script>
	export default {
		name: 'Ascii',
	}
</script>

// angular/epsic-burkhalter-dev/src/app/bin-module/components/ascii/ascii.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";

@Component({
  selector: 'app-ascii',
  templateUrl: './ascii.component.html',
  styleUrls: ['./ascii.component.css']
})
export class AsciiComponent implements OnInit {

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Code ASCII");
  }

  ngOnInit(): void {
  }

}

<h1>Code ASCII</h1>
<p>L'acronyme ASCII signifie American Standard Code for Information Interchange (Code américain normalisé pour l'échange d'information).</p>
<ul>
	<li>L'ASCII se code sur 7 bits, soit 128 caractères.</li>
	<li>L'ASCII étendu se code sur 8 bits, soit 256 caractères.</li>
</ul>

<h3>Table ASCII</h3>
<p>Les 32 premiers caractères (0 à 31) et le dernier (127) ne sont pas directement utilisables, ils étaient utilisé par la machines pour différentes choses</p>
<div class="row">
	<div class="col-xs-3">
		<table style="text-align: center; border: 1px solid black;" cellpadding="0">
			<tr><th>Décimale&nbsp;</th><th>Hexadécimale&nbsp;</th><th>ASCII&nbsp;</th></tr>
			<tr><td>0</td><td>0</td><td><i>NUL</i></td></tr>
			<tr><td>1</td><td>1</td><td><i>SOH</i></td></tr>
			<tr><td>2</td><td>2</td><td><i>STX</i></td></tr>
			<tr><td>3</td><td>3</td><td><i>ETX</i></td></tr>
			<tr><td>4</td><td>4</td><td><i>EOT</i></td></tr>
			<tr><td>5</td><td>5</td><td><i>ENQ</i></td></tr>
			<tr><td>6</td><td>6</td><td><i>ACK</i></td></tr>
			<tr><td>7</td><td>7</td><td><i>BEL</i></td></tr>
			<tr><td>8</td><td>8</td><td><i>BS</i></td></tr>
			<tr><td>9</td><td>9</td><td><i>HT</i></td></tr>
			<tr><td>10</td><td>0A</td><td><i>LF</i></td></tr>
			<tr><td>11</td><td>0B</td><td><i>VT</i></td></tr>
			<tr><td>12</td><td>0C</td><td><i>FF</i></td></tr>
			<tr><td>13</td><td>0D</td><td><i>CR</i></td></tr>
			<tr><td>14</td><td>0E</td><td><i>SO</i></td></tr>
			<tr><td>15</td><td>0F</td><td><i>SI</i></td></tr>
			<tr><td>16</td><td>10</td><td><i>DLE</i></td></tr>
			<tr><td>17</td><td>11</td><td><i>DC1</i></td></tr>
			<tr><td>18</td><td>12</td><td><i>DC2</i></td></tr>
			<tr><td>19</td><td>13</td><td><i>DC3</i></td></tr>
			<tr><td>20</td><td>14</td><td><i>DC4</i></td></tr>
			<tr><td>21</td><td>15</td><td><i>NAK</i></td></tr>
			<tr><td>22</td><td>16</td><td><i>SYN</i></td></tr>
			<tr><td>23</td><td>17</td><td><i>ETB</i></td></tr>
			<tr><td>24</td><td>18</td><td><i>CAN</i></td></tr>
			<tr><td>25</td><td>19</td><td><i>EM</i></td></tr>
			<tr><td>26</td><td>1A</td><td><i>SUB</i></td></tr>
			<tr><td>27</td><td>1B</td><td><i>ESC</i></td></tr>
			<tr><td>28</td><td>1C</td><td><i>FS</i></td></tr>
			<tr><td>29</td><td>1D</td><td><i>GS</i></td></tr>
			<tr><td>30</td><td>1E</td><td><i>RS</i></td></tr>
			<tr><td>31</td><td>1F</td><td><i>US</i></td></tr>
		</table>
	</div>
	<div class="col-xs-3">
		<table style="text-align: center; border: 1px solid black" cellpadding="0">
			<tr><th>Décimale&nbsp;</th><th>Hexadécimale&nbsp;</th><th>ASCII&nbsp;</th></tr>
			<tr><td>32</td><td>20</td><td>SP (Space)</td></tr>
			<tr><td>33</td><td>21</td><td>!</td></tr>
			<tr><td>34</td><td>22</td><td>"</td></tr>
			<tr><td>35</td><td>23</td><td>#</td></tr>
			<tr><td>36</td><td>24</td><td>$</td></tr>
			<tr><td>37</td><td>25</td><td>%</td></tr>
			<tr><td>38</td><td>26</td><td>&</td></tr>
			<tr><td>39</td><td>27</td><td>'</td></tr>
			<tr><td>40</td><td>28</td><td>(</td></tr>
			<tr><td>41</td><td>29</td><td>)</td></tr>
			<tr><td>42</td><td>2A</td><td>*</td></tr>
			<tr><td>43</td><td>2B</td><td>+</td></tr>
			<tr><td>44</td><td>2C</td><td>,</td></tr>
			<tr><td>45</td><td>2D</td><td>-</td></tr>
			<tr><td>46</td><td>2E</td><td>.</td></tr>
			<tr><td>47</td><td>2F</td><td>/</td></tr>
			<tr><td>48</td><td>30</td><td>0</td></tr>
			<tr><td>49</td><td>31</td><td>1</td></tr>
			<tr><td>50</td><td>32</td><td>2</td></tr>
			<tr><td>51</td><td>33</td><td>3</td></tr>
			<tr><td>52</td><td>34</td><td>4</td></tr>
			<tr><td>53</td><td>35</td><td>5</td></tr>
			<tr><td>54</td><td>36</td><td>6</td></tr>
			<tr><td>55</td><td>37</td><td>7</td></tr>
			<tr><td>56</td><td>38</td><td>8</td></tr>
			<tr><td>57</td><td>39</td><td>9</td></tr>
			<tr><td>58</td><td>3A</td><td>:</td></tr>
			<tr><td>59</td><td>3B</td><td>;</td></tr>
			<tr><td>60</td><td>3C</td><td>&lt;</td></tr>
			<tr><td>61</td><td>3D</td><td>=</td></tr>
			<tr><td>62</td><td>3E</td><td>&gt;</td></tr>
			<tr><td>63</td><td>3F</td><td>?</td></tr>
		</table>
	</div>
	<div class="col-xs-3">
		<table style="text-align: center; border: 1px solid black" cellpadding="0">
			<tr><th>Décimale&nbsp;</th><th>Hexadécimale&nbsp;</th><th>ASCII&nbsp;</th></tr>
			<tr><td>64</td><td>40</td><td>@</td></tr>
			<tr><td>65</td><td>41</td><td>A</td></tr>
			<tr><td>66</td><td>42</td><td>B</td></tr>
			<tr><td>67</td><td>43</td><td>C</td></tr>
			<tr><td>68</td><td>44</td><td>D</td></tr>
			<tr><td>69</td><td>45</td><td>E</td></tr>
			<tr><td>70</td><td>46</td><td>F</td></tr>
			<tr><td>71</td><td>47</td><td>G</td></tr>
			<tr><td>72</td><td>48</td><td>H</td></tr>
			<tr><td>73</td><td>49</td><td>I</td></tr>
			<tr><td>74</td><td>4A</td><td>J</td></tr>
			<tr><td>75</td><td>4B</td><td>K</td></tr>
			<tr><td>76</td><td>4C</td><td>L</td></tr>
			<tr><td>77</td><td>4D</td><td>M</td></tr>
			<tr><td>78</td><td>4E</td><td>N</td></tr>
			<tr><td>79</td><td>4F</td><td>O</td></tr>
			<tr><td>80</td><td>50</td><td>P</td></tr>
			<tr><td>81</td><td>51</td><td>Q</td></tr>
			<tr><td>82</td><td>52</td><td>R</td></tr>
			<tr><td>83</td><td>53</td><td>S</td></tr>
			<tr><td>84</td><td>54</td><td>T</td></tr>
			<tr><td>85</td><td>55</td><td>U</td></tr>
			<tr><td>86</td><td>56</td><td>V</td></tr>
			<tr><td>87</td><td>57</td><td>W</td></tr>
			<tr><td>88</td><td>58</td><td>X</td></tr>
			<tr><td>89</td><td>59</td><td>Y</td></tr>
			<tr><td>90</td><td>5A</td><td>Z</td></tr>
			<tr><td>91</td><td>5B</td><td>[</td></tr>
			<tr><td>92</td><td>5C</td><td>\</td></tr>
			<tr><td>93</td><td>5D</td><td>]</td></tr>
			<tr><td>94</td><td>5E</td><td>^</td></tr>
			<tr><td>95</td><td>5F</td><td>_</td></tr>
		</table>
	</div>
	<div class="col-xs-3">
		<table style="text-align: center; border: 1px solid black" cellpadding="0">
			<tr><th>Décimale&nbsp;</th><th>Hexadécimale&nbsp;</th><th>ASCII&nbsp;</th></tr>
			<tr><td>96</td><td>60</td><td>`</td></tr>
			<tr><td>97</td><td>61</td><td>a</td></tr>
			<tr><td>98</td><td>62</td><td>b</td></tr>
			<tr><td>99</td><td>63</td><td>c</td></tr>
			<tr><td>100</td><td>64</td><td>d</td></tr>
			<tr><td>101</td><td>65</td><td>e</td></tr>
			<tr><td>102</td><td>66</td><td>f</td></tr>
			<tr><td>103</td><td>67</td><td>g</td></tr>
			<tr><td>104</td><td>68</td><td>h</td></tr>
			<tr><td>105</td><td>69</td><td>i</td></tr>
			<tr><td>106</td><td>6A</td><td>j</td></tr>
			<tr><td>107</td><td>6B</td><td>k</td></tr>
			<tr><td>108</td><td>6C</td><td>l</td></tr>
			<tr><td>109</td><td>6D</td><td>m</td></tr>
			<tr><td>110</td><td>6E</td><td>n</td></tr>
			<tr><td>111</td><td>6F</td><td>o</td></tr>
			<tr><td>112</td><td>70</td><td>p</td></tr>
			<tr><td>113</td><td>71</td><td>q</td></tr>
			<tr><td>114</td><td>72</td><td>r</td></tr>
			<tr><td>115</td><td>73</td><td>s</td></tr>
			<tr><td>116</td><td>74</td><td>t</td></tr>
			<tr><td>117</td><td>75</td><td>u</td></tr>
			<tr><td>118</td><td>76</td><td>v</td></tr>
			<tr><td>119</td><td>77</td><td>w</td></tr>
			<tr><td>120</td><td>78</td><td>x</td></tr>
			<tr><td>121</td><td>79</td><td>y</td></tr>
			<tr><td>122</td><td>7A</td><td>z</td></tr>
			<tr><td>123</td><td>7B</td><td>&lcub;</td></tr>
			<tr><td>124</td><td>7C</td><td>|</td></tr>
			<tr><td>125</td><td>7D</td><td>}</td></tr>
			<tr><td>126</td><td>7E</td><td>~</td></tr>
			<tr><td>127</td><td>7F</td><td><i>DEL</i></td></tr>
		</table>
	</div>
</div>
<br>

<h3>ASCII étendu</h3>
<p>Le code ASCII étendu utilise 8 bits (au lieu de 7 pour l'ASCII). Il n'est cependant pas normalisé. Il est donc possible de voir des tables différentes de celle-ci :</p>
<img src="/medias/bin/extended_ascii.jpg" alt="Table ASCII étendu" />
