// src/modules/tools/views/Base64.vue
<script setup>
import { ref } from "vue"

const content = ref("")
const base64 = ref("")
const msg = ref("")

const toBase64 = () => {
  base64.value = window.btoa(encodeURIComponent(content.value))
  msg.value = ""
}
const fromBase64 = () => {
  try {
    content.value = decodeURIComponent(window.atob(base64.value))
    msg.value = ""
  } catch (e) {
    msg.value = "Base64 invalide !"
  }
}
</script>

<template>
  <div class="grid grid-cols-2 p-1 -m-1 gap-1.5 h-96 overflow-y-auto resize-y">
    <div class="w-full flex flex-col gap-1.5">
      <label for="content" class="block font-semibold">Valeur :</label>
      <textarea
        id="content"
        v-model="content"
        @keyup="toBase64()"
        class="w-full border resize-none h-full"
      ></textarea>
    </div>
    <div class="w-full flex flex-col gap-1.5">
      <label for="base64" class="block font-semibold">Base64 :</label>
      <textarea
        id="base64"
        v-model="base64"
        @keyup="fromBase64()"
        class="w-full border resize-none h-full"
      ></textarea>
      <div v-if="msg" class="alert-danger !my-0">{{ msg }}</div>
    </div>
  </div>
</template>

// src/app/tools-module/components/base64/base64.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";

@Component({
  selector: 'app-base64',
  templateUrl: './base64.component.html',
  styleUrls: ['./base64.component.css']
})
export class Base64Component implements OnInit {

  public content: string = "";
  public base64: string = "";
  public msg: string = "";

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Conversion Base64");
  }

  ngOnInit(): void {
  }

  public toBase64(): void {
    this.base64 = window.btoa(unescape(encodeURIComponent(this.content)));
  }

  public fromBase64(): void {
    try {
      this.content = decodeURIComponent(escape(window.atob(this.base64)));
      this.msg = '';
    } catch(e) {
      this.msg = 'Base64 invalide.';
    }
  }
}

<h1>Conversion Base64</h1>
<strong>Valeur :</strong><br>
<textarea class="w-100" [(ngModel)]="content" (ngModelChange)="toBase64()"></textarea><br>
<br>
<strong>Base64 :</strong><br>
<textarea class="w-100" [(ngModel)]="base64" (ngModelChange)="fromBase64()"></textarea><br>
<p class="text-danger">{{ msg }}</p>
