// src/views/tools/Base64.vue
<template>
	<div>
		<h1>Conversion Base64</h1>
		<strong>Valeur :</strong><br>
		<textarea class="w-100" v-model="content" @keyup="toBase64()"></textarea><br>
		<br>
		<strong>Base64 :</strong><br>
		<textarea class="w-100" v-model="base64" @keyup="fromBase64()"></textarea><br>
		<p class="text-danger">{{ msg }}</p>
	</div>
</template>

<script>
	export default {
		name: 'Base64',
		data() {
			return {
				content: '',
				base64: '',
				msg: '',
			}
		},
		methods: {
			toBase64() {
				this.base64 = window.btoa(unescape(encodeURIComponent(this.content)));
			},
			fromBase64() {
			try {
				this.content = decodeURIComponent(escape(window.atob(this.base64)));
				this.msg = '';
			} catch(e) {
				this.msg = 'Base64 invalide.';
			}
			},
		}
	}
</script>

// src/app/tools-module/components/base64/base64.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";

@Component({
  selector: 'app-base64',
  templateUrl: './base64.component.html',
  styleUrls: ['./base64.component.css']
})
export class Base64Component implements OnInit {

  public content: string = "";
  public base64: string = "";
  public msg: string = "";

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Conversion Base64");
  }

  ngOnInit(): void {
  }

  public toBase64(): void {
    this.base64 = window.btoa(unescape(encodeURIComponent(this.content)));
  }

  public fromBase64(): void {
    try {
      this.content = decodeURIComponent(escape(window.atob(this.base64)));
      this.msg = '';
    } catch(e) {
      this.msg = 'Base64 invalide.';
    }
  }
}

<h1>Conversion Base64</h1>
<strong>Valeur :</strong><br>
<textarea class="w-100" [(ngModel)]="content" (ngModelChange)="toBase64()"></textarea><br>
<br>
<strong>Base64 :</strong><br>
<textarea class="w-100" [(ngModel)]="base64" (ngModelChange)="fromBase64()"></textarea><br>
<p class="text-danger">{{ msg }}</p>
