// angular/epsic-burkhalter-dev/src/app/access-module/components/control-zone-liste/control-zone-liste.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";
import 'prismjs/components/prism-visual-basic';

declare var Prism: any;

@Component({
  selector: 'app-control-zone-liste',
  templateUrl: './control-zone-liste.component.html',
  styleUrls: ['./control-zone-liste.component.css']
})
export class ControlZoneListeComponent implements OnInit {

  public Prism: any = {};

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Importer, ajouter, modifier et supprimer des éléments d'une zone de liste (niveau avancé)");
    this.Prism = Prism;
  }

  ngOnInit(): void {
  }

}

<h1>Importer, ajouter, modifier et supprimer des éléments d'une zone de liste (niveau avancé)</h1>
<p>Ici, nous allons permettre d'interagir avec la zone de liste crée dans le chapitre précèdent. J'insiste sur le terme 'avancé' car nous allons utiliser ~ beaucoup de VBA. J'essaierais d'expliquer au mieux.</p>
<p>Commencez par créer 4 boutons :</p>
<ul>
	<li>Un pour l'importation d'une adresse email (par importation, j'entends ajouter un email qui existe déjà)</li>
	<li>Un pour la création d'une adresse email</li>
	<li>Un pour la suppression d'une adresse email</li>
	<li>Un pour l'édition d'une adresse email</li>
</ul>
<img src="/medias/access/icud.png" />
<p>Choisissez des icônes qui vous parlent, ne leur donné pas de fonctions pour l'instant.</p>

<h3>Ajouter une adresse</h3>
<p>Commençons par le bouton permettant d'ajouter une adresse email.</p>
<p>Il faut utiliser l'assistant de formulaire et inclure aussi l'ID :</p>
<img src="/medias/access/icud_c1.png" />
<p>Nommez le formulaire F_Ajouter_Email, car nous devrons en faire un par fonction.</p>
<p>Ajoutez-y un bouton avec la fonction Sauvegarder un enregistrement</p>
<img src="/medias/access/icud_c2.png" />
<p>Maintenant, passons aux choses sérieuses. Allez dans les propriétés du formulaire, sous Événement, cliquer sur Après insertion</p>
<img src="/medias/access/icud_c3.png" />
<p>L'éditeur VBA s'ouvre, collez-y le code suivant :</p>
<pre class="language-visual-basic"><code [innerHTML]="Form_AfterInsert"></code></pre>
<p>Explication du code :</p>
<p>La deuxième ligne (DoCmd.RunSQL) permet d'exécuter une requête SQL, pour faire simple, c'est une manière de modifier la base de données depuis le code. Pensez a remplacer tous les noms de champs par les vôtres, sinon Access ne les trouveras pas.</p>
<p>Seulement, cette fonction affiche un avertissement, nous mettons donc la commande DoCmd.SetWarnings False avant afin de les désactiver et DoCmd.SetWarnings True après pour les réactiver.</p>
<p>DoCmd.Close ferme simplement le formulaire donc on devrait être retourné sur le formulaire F_Personne.</p>
<p>Pour finir, on fait un Requery sur le champ Emails de F_Personne pour l'actualiser et donc afficher la nouvelle adresse ajoutée.</p>
<p>Il faut ensuite retourner dans F_Personne et ajouter un évènement Sur clic au bouton + :</p>
<pre class="language-visual-basic"><code [innerHTML]="Btn_ajouter_email_Click"></code></pre>
<p>Cela ouvrira le formulaire F_Ajouter_Email</p>

<h3>Importer une adresse</h3>
<p>Importer n'est peut-être pas le meilleur terme. Je veux dire par là, associer une adresse déjà existante a la personne.</p>
<p>Commencez par créer un nouveau formulaire avec l'assistant. Nommez le F_Importer_Email (par exemple) puis supprimez-y tous les champs.</p>
<p>Insérez à la place une Zone de liste déroulante</p>
<img src="/medias/access/icud_i1.png" />
<p>Selectionnez T_Email</p>
<img src="/medias/access/icud_i2.png" />
<p>Prenez au moins l'ID et l'adresse</p>
<img src="/medias/access/icud_i3.png" />
<p>Il n'y a plus grand chose à configurer par la suite, vous pouvez faire suivant, suivant, suivant...</p>
<img src="/medias/access/icud_i4.png" />
<img src="/medias/access/icud_i5.png" />
<img src="/medias/access/icud_i6.png" />
<img src="/medias/access/icud_i7.png" />
<p>Une fois la liste déroulante créée, ajoutez un bouton, dans Événement, Sur clic, cela ouvre l'éditeur VBA.</p>
<p>Vous pouvez y coller le même code que précédemment, à l'exception de la requête SQL qui diffère un peu.</p>
<pre class="language-visual-basic"><code [innerHTML]="Btn_selectionner_Click"></code></pre>
<p>Et, ne pas oublier de donner un évènement au bouton v dans le formulaire F_Personne</p>
<pre class="language-visual-basic"><code [innerHTML]="Btn_importer_email_Click"></code></pre>

<h3>Supprimer une adresse</h3>
<p>Le bouton Supprimer n'aura pas pour effet de supprimer l'adresse, mais juste la relation entre la personne et l'adresse.</p>
<p>Ici, pas besoin de créer de formulaire. Allez dans les propriétés du bouton - et ajouté un l'événement Sur clic.</p>
<pre class="language-visual-basic"><code [innerHTML]="Btn_supprimer_email_Click"></code></pre>
<p>Nous avons ici 2 condition, la première c'est qu'il y ai un élément sélectionné dans la liste, la deuxième c'est que l'utilisateur confirme la suppression.</p>
<p>Ensuite, ça lance du SQL comme avant et réactualise le champ.</p>
<p>Il vous faudra surement renommer quelques trucs pour que cela marche.</p>

<h3>Modifier une adresse</h3>
<p>La modification est très proche de la création. Vous pouvez déjà copier-coller le formulaire F_Ajouter_Email et le renommer F_Modifier_Email.</p>
<p>Dans les événements, supprimer le Après insertion et cliquez sur Après MAJ.</p>
<p>Le code est très simple, je pense qu'il n'y a même pas besoin de l'expliquer :</p>
<pre class="language-visual-basic"><code [innerHTML]="Form_AfterUpdate"></code></pre>
<p>Il faut aussi mettre un peu de code sur le bouton d'édition :</p>
<pre class="language-visual-basic"><code [innerHTML]="Btn_modifier_email_Click"></code></pre>
<p>Je fais juste un petit test pour voir si un élément est sélectionné.</p>

<p>Voilà, tous les boutons devraient maintenant marcher. Le fichier est disponible <a href="/medias/access/Database2.accdb">ici</a> si vous voulez vérifier ou comparer quelque chose.</p>

// src/modules/access/views/ControlZoneListe.vue
<script setup>
import ShowCode from "@/components/ShowCode.vue"
</script>

<template>
  <div>
    <p>
      Ici, nous allons permettre d'interagir avec la zone de liste créée dans le
      chapitre précédent. J'insiste sur le terme "avancé" car nous allons
      utiliser beaucoup de VBA. J'essaierai d'expliquer au mieux.
    </p>
    <p>Commencez par créer 4 boutons :</p>
    <ul>
      <li>
        <span
          >Un pour l'importation d'une adresse e-mail (par importation,
          j'entends ajouter un e-mail qui existe déjà)</span
        >
      </li>
      <li><span>Un pour la création d'une adresse e-mail</span></li>
      <li><span>Un pour la suppression d'une adresse e-mail</span></li>
      <li><span>Un pour l'édition d'une adresse e-mail</span></li>
    </ul>
    <img src="/access/medias/icud.png" />
    <p>
      Choisissez des icônes qui vous parlent. Ne leur donnez pas de fonctions
      pour l'instant.
    </p>

    <h2>Ajouter une adresse</h2>
    <p>Commençons par le bouton permettant d'ajouter une adresse e-mail.</p>
    <p>Il faut utiliser l'assistant de formulaire et inclure aussi l'ID :</p>
    <img src="/access/medias/icud_c1.png" />
    <p>
      Nommez le formulaire F_Ajouter_Email car nous devrons en faire un par
      fonction.
    </p>
    <p>
      Ajoutez-y un bouton avec la fonction
      <i>Sauvegarder un enregistrement</i> :
    </p>
    <img src="/access/medias/icud_c2.png" />
    <p>
      Maintenant, passons aux choses sérieuses. Allez dans les propriétés du
      formulaire, et, sous <i>Événement</i>, cliquez sur
      <i>Après insertion</i> :
    </p>
    <img src="/access/medias/icud_c3.png" />
    <p>L'éditeur VBA s'ouvre. Collez-y le code suivant :</p>
    <ShowCode file="/access/code/Form_AfterInsert.vba" lang="vba" />
    <p>Explication du code :</p>
    <p>
      La deuxième ligne (<code>DoCmd.RunSQL</code>) permet d'exécuter une
      requête SQL. Pour faire simple, c'est une manière de modifier la base de
      données depuis le code. Pensez a remplacer tous les noms de champs par les
      vôtres, sinon Access ne les trouvera pas.
    </p>
    <p>
      Seulement, cette fonction affiche un avertissement, nous mettons donc la
      commande <code>DoCmd.SetWarnings False</code> avant afin de les désactiver
      et <code>DoCmd.SetWarnings True</code> pour les réactiver après.
    </p>
    <p>
      <code>DoCmd.Close</code> ferme simplement le formulaire, nous renvoyant
      ainsi vers le formulaire F_Personne.
    </p>
    <p>
      Pour finir, on fait un <code>Requery</code> sur le champ Emails de
      F_Personne pour l'actualiser et donc afficher la nouvelle adresse ajoutée.
    </p>
    <p>
      Il faut ensuite retourner dans F_Personne et ajouter un évènement
      <i>Sur clic</i> au bouton + :
    </p>
    <ShowCode file="/access/code/Btn_ajouter_email_Click.vba" lang="vba" />
    <p>Cela ouvrira le formulaire F_Ajouter_Email.</p>

    <h2>Importer une adresse</h2>
    <p>
      Importer n'est peut-être pas le meilleur terme. Je veux dire par là,
      associer une adresse déjà existante à la personne.
    </p>
    <p>
      Commencez par créer un nouveau formulaire avec l'assistant. Nommez-le
      F_Importer_Email (par exemple), puis supprimez-y tous les champs.
    </p>
    <p>À la place, insérez une <i>Zone de liste déroulante</i> :</p>
    <img src="/access/medias/icud_i1.png" />
    <p>Selectionnez T_Email :</p>
    <img src="/access/medias/icud_i2.png" />
    <p>Prenez au moins l'ID et l'adresse :</p>
    <img src="/access/medias/icud_i3.png" />
    <p>
      Il n'y a plus grand chose à configurer par la suite, vous pouvez faire
      suivant, suivant, suivant...
    </p>
    <img src="/access/medias/icud_i4.png" />
    <img src="/access/medias/icud_i5.png" />
    <img src="/access/medias/icud_i6.png" />
    <img src="/access/medias/icud_i7.png" />
    <p>
      Une fois la liste déroulante créée, ajoutez un bouton, dans
      <i>Événement</i> → <i>Sur clic</i>. Cela ouvre l'éditeur VBA.
    </p>
    <p>
      Vous pouvez y coller le même code que précédemment, à l'exception de la
      requête SQL qui diffère un peu :
    </p>
    <ShowCode file="/access/code/Btn_selectionner_Click.vba" lang="vba" />
    <p>
      Et, ne pas oublier de donner un évènement au bouton v dans le formulaire
      F_Personne :
    </p>
    <ShowCode file="/access/code/Btn_importer_email_Click.vba" lang="vba" />

    <h2>Supprimer une adresse</h2>
    <p>
      Le bouton <i>Supprimer</i> n'aura pas pour effet de supprimer l'adresse,
      mais juste la relation entre la personne et l'adresse.
    </p>
    <p>
      Ici, pas besoin de créer de formulaire. Allez dans les propriétés du
      bouton et ajouté un l'événement <i>Sur clic</i> :
    </p>
    <ShowCode file="/access/code/Btn_supprimer_email_Click.vba" lang="vba" />
    <p>
      Nous avons ici deux conditions. La première est qu'il y ai un élément
      sélectionné dans la liste. La deuxième est que l'utilisateur confirme la
      suppression.
    </p>
    <p>Ensuite, ça lance du SQL comme avant et réactualise le champ.</p>
    <p>Il vous faudra sûrement renommer quelques trucs pour que cela marche.</p>

    <h2>Modifier une adresse</h2>
    <p>
      La modification est très proche de la création. Vous pouvez déjà
      copier-coller le formulaire F_Ajouter_Email et le renommer
      F_Modifier_Email.
    </p>
    <p>
      Dans les événements, supprimez-le <i>Après insertion</i> et cliquez sur
      <i>Après MAJ</i>.
    </p>
    <p>
      Le code est très simple, je pense qu'il n'y a même pas besoin de
      l'expliquer :
    </p>
    <ShowCode file="/access/code/Form_AfterUpdate.vba" lang="vba" />
    <p>Il faut aussi mettre un peu de code sur le bouton d'édition :</p>
    <ShowCode file="/access/code/Btn_modifier_email_Click.vba" lang="vba" />
    <p>Je fais juste un petit test pour voir si un élément est sélectionné.</p>

    <p>
      Voilà ! Tous les boutons devraient maintenant fonctionner. Le fichier est
      disponible <a href="/access/files/Database2.accdb">ici</a> si vous voulez
      vérifier ou comparer quelque chose.
    </p>
  </div>
</template>

<style scoped>
code {
  @apply bg-gray-200;
}
</style>
