// src/views/network/CalculateurSr.vue
<template>
  <div>
    <h1>Calculateur de sous-réseaux</h1>
    <label for="ip">Nombre max de machines (sans le routeur) :</label
    >&nbsp;<input type="number" v-model="nbIPstr" /><br />
    <label for="sr">Nombre max de sous-réseaux :</label>&nbsp;<input
      type="number"
      v-model="nbSRstr"
    /><br />
    <button type="button" @click="calculate()">Calculer</button><br /><br />
    <h3>1) Déterminer les besoins (inclure les réserves)</h3>
    <p v-html="step1o_ip"></p>
    <p v-html="step1o_sr"></p>
    <h3>
      2) Calculer et réserver le nombre de bits nécessaires (Host_ID et
      Subnet_ID)
    </h3>
    <p v-html="step2o_ip"></p>
    <p v-html="step2o_sr"></p>
    <h3>3) Définir la classe et le Net_ID</h3>
    <p v-html="step3o_classe"></p>
    <p v-html="step3o_net_id"></p>
    <p v-html="step35o"></p>
    <h3>4) Déterminer le masque (réseau et sous-réseau)</h3>
    <p v-html="step4o"></p>
    <h3>5) Calculer les adresses de chaque sous-réseau</h3>
    <p v-html="step5o"></p>
    <h3>6) Réaliser l'annuaire</h3>
    <table class="table">
      <tr>
        <th>Adresse du sous-réseau</th>
        <th>Première adresse IP</th>
        <th>Dernière adresse IP</th>
        <th>Adresse de diffusion</th>
      </tr>
      <tr v-for="sr of step6o" :key="sr">
        <td>{{ sr[0] }}</td>
        <td>{{ sr[1] }}</td>
        <td>{{ sr[2] }}</td>
        <td>{{ sr[3] }}</td>
      </tr>
    </table>
  </div>
</template>

<script>
export default {
  name: "CalculateurSr",
  data() {
    return {
      nbIPstr: "",
      nbSRstr: "",
      nbIP: 0,
      nbSR: 0,
      n_IP: 0,
      n_SR: 0,
      n_R: 0,
      classe: "",
      NET_ID: 0,
      MASK: 0,
      SR: new Array(),
      step1o_ip: "",
      step1o_sr: "",
      step2o_ip: "",
      step2o_sr: "",
      step3o_classe: "",
      step3o_net_id: "",
      step35o: "",
      step4o: "",
      step5o: "",
      step6o: new Array(),
    }
  },
  methods: {
    calculate() {
      this.nbIP = parseInt(this.nbIPstr)
      this.nbSR = parseInt(this.nbSRstr)

      if (this.nbIP > 0 && this.nbSR > 0) {
        this.step1()
        this.step2()
        this.step3()
        this.step35()
        this.step4()
        this.step5()
        this.step6()
      } else {
        this.step1o_ip = ""
        this.step1o_sr = ""
        this.step2o_ip = ""
        this.step2o_sr = ""
        this.step3o_classe = ""
        this.step3o_net_id = ""
        this.step35o = ""
        this.step4o = ""
        this.step5o = ""
        this.step6o = []
      }
    },
    step1() {
      this.step1o_ip = this.nbIP.toString()
      this.nbIP++
      this.step1o_ip += " + 1 (passerelle) = " + this.nbIP
      this.step1o_ip += "<br>" + this.nbIP
      this.nbIP += Math.ceil(this.nbIP / 10)
      this.step1o_ip += " + 10% = " + this.nbIP

      this.step1o_sr = this.nbSR.toString()
      this.nbSR += Math.ceil(this.nbSR / 10)
      this.step1o_sr += " + 10% = " + this.nbSR
    },
    step2() {
      this.n_IP = this.ln(this.nbIP + 2) / this.ln(2)
      this.step2o_ip =
        "n = ln(" + this.nbIP + " + 2) / ln(2) = ~" + this.n_IP.toFixed(4)
      this.n_IP = Math.ceil(this.n_IP)
      this.step2o_ip += " → " + this.n_IP

      this.n_SR = this.ln(this.nbSR + 2) / this.ln(2)
      this.step2o_sr =
        "n = ln(" + this.nbSR + " + 2) / ln(2) = ~" + this.n_SR.toFixed(4)
      this.n_SR = Math.ceil(this.n_SR)
      this.step2o_sr += " → " + this.n_SR
    },
    step3() {
      if (this.n_IP + this.n_SR <= 8) {
        this.classe = "C"
        this.NET_ID = this.ipToNumber([192, 168, 1, 0])
        this.n_R = 24
        this.step3o_classe = this.n_IP + " + " + this.n_SR + " ≤ 8 → Classe C"
      } else if (this.n_IP + this.n_SR <= 16) {
        this.classe = "B"
        this.NET_ID = this.ipToNumber([172, 16, 0, 0])
        this.n_R = 16
        this.step3o_classe = this.n_IP + " + " + this.n_SR + " ≤ 16 → Classe B"
      } else if (this.n_IP + this.n_SR <= 24) {
        this.classe = "A"
        this.NET_ID = this.ipToNumber([10, 0, 0, 0])
        this.n_R = 8
        this.step3o_classe = this.n_IP + " + " + this.n_SR + " ≤ 24 → Classe A"
      }
      this.step3o_net_id =
        "NET_ID : " + this.showIP(this.numberToIp(this.NET_ID))
    },
    step35() {
      let n_IP = this.n_IP
      let n_SR = this.n_SR
      if (this.n_IP + this.n_SR <= 8) {
        this.n_IP += 8 - this.n_IP - this.n_SR
      } else if (this.n_IP + this.n_SR <= 16) {
        if (this.n_IP <= 8 && this.n_SR <= 8) {
          this.n_IP = 8
          this.n_SR = 8
        } else {
          this.n_IP += 16 - this.n_IP - this.n_SR
        }
      } else if (this.n_IP + this.n_SR <= 24) {
        if (this.n_IP <= 8 && this.n_SR <= 16) {
          this.n_IP = 8
          this.n_SR = 16
        } else if (this.n_IP <= 16 && this.n_SR <= 8) {
          this.n_IP = 16
          this.n_SR = 18
        } else {
          this.n_IP += 24 - this.n_IP - this.n_SR
        }
      }
      if (this.n_IP != n_IP || this.n_SR != n_SR) {
        let calcul_IP = n_IP + " → " + this.n_IP
        let calcul_SR = n_SR + " → " + this.n_SR
        this.step35o = calcul_IP + "<br>" + calcul_SR
      } else {
        this.step35o = ""
      }

      this.nbIP = Math.pow(2, this.n_IP) - 2
      this.nbSR = Math.pow(2, this.n_SR) - 2
    },
    step4() {
      this.MASK = this.n_R + this.n_SR
      this.step4o = "MASK : " + this.showIP(this.showMask(this.MASK))
    },
    step5() {
      this.step5o = ""
      let step = Math.pow(2, this.n_IP)
      this.SR = new Array(this.nbSR + 1)
      for (let i = 0; i < this.SR.length; i++) {
        if (i == 0) {
          this.SR[i] = this.NET_ID + step
        } else {
          this.SR[i] = this.SR[i - 1] + step
        }
        if (i < this.SR.length - 1) {
          if (i < 9 || i == this.SR.length - 2) {
            if (i > 0) {
              this.step5o += "<br>"
              if (i > 9 && i == this.SR.length - 2) {
                this.step5o += "...<br>"
              }
            }
            this.step5o += this.showIP(this.numberToIp(this.SR[i]))
          }
        }
      }
    },
    step6() {
      this.step6o = []
      for (let i = 0; i < this.SR.length - 1; i++) {
        this.step6o.push([
          this.showIP(this.numberToIp(this.SR[i])),
          this.showIP(this.numberToIp(this.SR[i] + 1)),
          this.showIP(this.numberToIp(this.SR[i + 1] - 2)),
          this.showIP(this.numberToIp(this.SR[i + 1] - 1)),
        ])
      }
    },
    ln(a) {
      return Math.log(a) / Math.log(Math.E)
    },
    showIP(ip) {
      let result = ""
      for (let k = 0; k < ip.length; k++) {
        if (k > 0) {
          result += "."
        }
        result += ip[k]
      }
      return result
    },
    showMask(mask) {
      let result = [0, 0, 0, 0]
      for (let k = 0; k < mask; k++) {
        result[Math.ceil((k + 1) / 8) - 1] += Math.pow(2, 7 - (k % 8))
      }
      return result
    },
    ipToNumber(ip) {
      let number = 0
      for (let k = 0; k < ip.length; k++) {
        number += ip[k] * Math.pow(256, 3 - k)
      }
      return number
    },
    numberToIp(number) {
      let ip = new Array(4)
      for (let k = 0; k < ip.length; k++) {
        let r = number % 256
        number = Math.floor(number / 256)
        ip[3 - k] = r
      }
      return ip
    },
  },
}
</script>

// angular/epsic-burkhalter-dev/src/app/network-module/components/calculateur-sr/calculateur-sr.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";

@Component({
  selector: 'app-calculateur-sr',
  templateUrl: './calculateur-sr.component.html',
  styleUrls: ['./calculateur-sr.component.css']
})
export class CalculateurSrComponent implements OnInit {

  public nbIPstr: string = "";
  public nbSRstr: string = "";
  private nbIP: number = 0;
  private nbSR: number = 0;
  private n_IP: number = 0;
  private n_SR: number = 0;
  private n_R: number = 0;
  private classe: string = "";
  private NET_ID: number = 0;
  private MASK: number = 0;
  private SR: number[] = new Array();

  public step1o_ip: string = "";
  public step1o_sr: string = "";
  public step2o_ip: string = "";
  public step2o_sr: string = "";
  public step3o_classe: string = "";
  public step3o_net_id: string = "";
  public step35o: string = "";
  public step4o: string = "";
  public step5o: string = "";
  public step6o: string[][] = new Array();

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Calculateur de sous-réseaux");
  }

  ngOnInit(): void {
  }

  public calculate(): void {
    this.nbIP = parseInt(this.nbIPstr);
    this.nbSR = parseInt(this.nbSRstr);

    if(this.nbIP > 0 && this.nbSR > 0){
      this.step1();
      this.step2();
      this.step3();
      this.step35();
      this.step4();
      this.step5();
      this.step6();
    } else {
      this.step1o_ip = "";
      this.step1o_sr = "";
      this.step2o_ip = "";
      this.step2o_sr = "";
      this.step3o_classe = "";
      this.step3o_net_id = "";
      this.step35o = "";
      this.step4o = "";
      this.step5o = "";
      this.step6o = [];
    }
  }

  private step1(): void {
    this.step1o_ip = this.nbIP.toString();
    this.nbIP++;
    this.step1o_ip += " + 1 (passerelle) = " + this.nbIP;
    this.step1o_ip += "<br>" + this.nbIP;
    this.nbIP += Math.ceil(this.nbIP/10);
    this.step1o_ip += " + 10% = " + this.nbIP;

    this.step1o_sr = this.nbSR.toString();
    this.nbSR += Math.ceil(this.nbSR/10);
    this.step1o_sr += " + 10% = " + this.nbSR;
  }

  private step2(): void {
    this.n_IP = this.ln(this.nbIP + 2) / this.ln(2);
    this.step2o_ip = "n = ln(" + this.nbIP + " + 2) / ln(2) = ~" + this.n_IP;
    this.n_IP = Math.ceil(this.n_IP);
    this.step2o_ip += " → " + this.n_IP;

    this.n_SR = this.ln(this.nbSR + 2) / this.ln(2);
    this.step2o_sr = "n = ln(" + this.nbSR + " + 2) / ln(2) = ~" + this.n_SR;
    this.n_SR = Math.ceil(this.n_SR);
    this.step2o_sr += " → " + this.n_SR;
  }

  private step3(): void {
    if(this.n_IP + this.n_SR <= 8){
      this.classe = "C";
      this.NET_ID = this.ipToNumber([192, 168, 1, 0]);
      this.n_R = 24;
      this.step3o_classe = this.n_IP + " + " + this.n_SR + " ≤ 8 → Classe C";
    } else if(this.n_IP + this.n_SR <= 16){
      this.classe = "B";
      this.NET_ID = this.ipToNumber([172, 16, 0, 0]);
      this.n_R = 16;
      this.step3o_classe = this.n_IP + " + " + this.n_SR + " ≤ 16 → Classe B";
    } else if(this.n_IP + this.n_SR <= 24){
      this.classe = "A";
      this.NET_ID = this.ipToNumber([10, 0, 0, 0]);
      this.n_R = 8;
      this.step3o_classe = this.n_IP + " + " + this.n_SR + " ≤ 24 → Classe A";
    }
    this.step3o_net_id = "NET_ID : " + this.showIP(this.numberToIp(this.NET_ID));
  }

  private step35(): void {
    let n_IP = this.n_IP;
    let n_SR = this.n_SR;
    if(this.n_IP + this.n_SR <= 8){
      this.n_IP += 8 - this.n_IP - this.n_SR;
    } else if(this.n_IP + this.n_SR <= 16){
      if(this.n_IP <= 8 && this.n_SR <= 8){
        this.n_IP = 8;
        this.n_SR = 8;
      } else {
        this.n_IP += 16 - this.n_IP - this.n_SR;
      }
    } else if(this.n_IP + this.n_SR <= 24){
      if(this.n_IP <= 8 && this.n_SR <= 16){
        this.n_IP = 8;
        this.n_SR = 16;
      } else if(this.n_IP <= 16 && this.n_SR <= 8){
        this.n_IP = 16;
        this.n_SR = 18;
      } else {
        this.n_IP += 24 - this.n_IP - this.n_SR;
      }
    }
    if(this.n_IP != n_IP || this.n_SR != n_SR){
      let calcul_IP = n_IP + " → " + this.n_IP;
      let calcul_SR = n_SR + " → " + this.n_SR;
      this.step35o = calcul_IP + "<br>" + calcul_SR;
    } else {
      this.step35o = "";
    }

    this.nbIP = Math.pow(2, this.n_IP) - 2;
    this.nbSR = Math.pow(2, this.n_SR) - 2;
  }

  private step4(): void {
    this.MASK = this.n_R + this.n_SR;
    this.step4o = "MASK : " + this.showIP(this.showMask(this.MASK));
  }

  private step5(): void {
    this.step5o = "";
    let step = Math.pow(2, this.n_IP);
    this.SR = new Array(this.nbSR + 1);
    for(let i = 0; i < this.SR.length; i++){
      if(i == 0){
        this.SR[i] = this.NET_ID + step;
      } else {
        this.SR[i] = this.SR[i-1] + step;
      }
      if(i < this.SR.length-1){
        if(i < 9 || i == this.SR.length-2){
          if(i > 0){
            this.step5o += "<br>";
            if(i > 9 && i == this.SR.length-2){
              this.step5o += "...<br>";
            }
          }
          this.step5o += this.showIP(this.numberToIp(this.SR[i]));
        }
      }
    }
  }

  private step6(): void {
    this.step6o = [];
    for(let i = 0; i < this.SR.length-1; i++){
      this.step6o.push([
        this.showIP(this.numberToIp(this.SR[i])),
        this.showIP(this.numberToIp(this.SR[i]+1)),
        this.showIP(this.numberToIp(this.SR[i+1]-2)),
        this.showIP(this.numberToIp(this.SR[i+1]-1))
      ]);
    }
  }

  private ln(a: number): number {
    return Math.log(a) / Math.log(Math.E);
  }

  private showIP(ip: number[]): string {
    let result = "";
    for(let k = 0; k < ip.length; k++){
      if(k > 0){
        result += ".";
      }
      result += ip[k];
    }
    return result;
  }

  private showMask(mask: number): number[] {
    let result = [0, 0, 0, 0];
    for(let k = 0; k < mask; k++){
      result[Math.ceil((k+1)/8)-1] += Math.pow(2, 7-(k % 8));
    }
    return result;
  }

  private ipToNumber(ip: number[]): number {
    let number = 0;
    for(let k = 0; k < ip.length; k++){
      number += ip[k] * Math.pow(256, 3-k);
    }
    return number;
  }

  private numberToIp(number: number): number[] {
    let ip = new Array(4);
    let r = 0;
    for(let k = 0; k < ip.length; k++){
      let r = number % 256;
      number = Math.floor(number / 256);
      ip[3-k] = r;
    }
    return ip;
  }
}

<h1>Calculateur de sous-réseaux</h1>
<label for="ip">Nombre max de machines (sans le routeur) :</label>&nbsp;<input type="number" [(ngModel)]="nbIPstr" (ngModelChange)="calculate()"><br>
<label for="sr">Nombre max de sous-réseaux :</label>&nbsp;<input type="number" [(ngModel)]="nbSRstr" (ngModelChange)="calculate()"><br>
<button type="button" (click)="calculate()">Calculer</button><br><br>
<h3>1) Déterminer les besoins (inclure les réserves)</h3>
<p [innerHTML]="step1o_ip"></p>
<p [innerHTML]="step1o_sr"></p>
<h3>2) Calculer et réserver le nombre de bits nécessaires (Host_ID et Subnet_ID)</h3>
<p [innerHTML]="step2o_ip"></p>
<p [innerHTML]="step2o_sr"></p>
<h3>3) Définir la classe et le Net_ID</h3>
<p [innerHTML]="step3o_classe"></p>
<p [innerHTML]="step3o_net_id"></p>
<p [innerHTML]="step35o"></p>
<h3>4) Déterminer le masque (réseau et sous-réseau)</h3>
<p [innerHTML]="step4o"></p>
<h3>5) Calculer les adresses de chaque sous-réseau</h3>
<p [innerHTML]="step5o"></p>
<h3>6) Réaliser l'annuaire</h3>
<table class="table">
	<tr>
		<th>Adresse du sous-réseau</th>
		<th>Première adresse IP</th>
		<th>Dernière adresse IP</th>
		<th>Adresse de diffusion</th>
	</tr>
	<tr *ngFor="let sr of step6o">
		<td>{{ sr[0] }}</td>
		<td>{{ sr[1] }}</td>
		<td>{{ sr[2] }}</td>
		<td>{{ sr[3] }}</td>
	</tr>
</table>
