// angular/epsic-burkhalter-dev/src/app/network-module/components/structure-ip/structure-ip.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";

@Component({
  selector: 'app-structure-ip',
  templateUrl: './structure-ip.component.html',
  styleUrls: ['./structure-ip.component.css']
})
export class StructureIpComponent implements OnInit {

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Structure d'une adresse IP");
  }

  ngOnInit(): void {
  }

}

<h1>Structure d'une adresse IP</h1>

<p style="text-align: center;"><span style="background-color: lightgray;"><strong><span style="color: red;">[ NET_ID ]</span>&nbsp;<span style="color: blue;">[ HOST_ID ]</span></strong></span></p>
<p style="text-align: center;">Classe A: <span style="background-color: lightgray;"><strong><span style="color: red;">x</span>.<span style="color: blue;">x.x.x</span></strong></span></p>
<p style="text-align: center;">Classe B: <span style="background-color: lightgray;"><strong><span style="color: red;">x.x</span>.<span style="color: blue;">x.x</span></strong></span></p>
<p style="text-align: center;">Classe C: <span style="background-color: lightgray;"><strong><span style="color: red;">x.x.x</span>.<span style="color: blue;">x</span></strong></span></p>
<hr>
<p style="text-align: center;"><span style="background-color: lightgray;"><strong><span style="color: red;">[ NET_ID ]</span>&nbsp;<span style="color: green;">[ SUBNET_ID ]</span>&nbsp;<span style="color: blue;">[ HOST_ID ]</span></strong></span></p>
<p>S'il y a un sous-réseau, le SUBNET_ID ce calcul comme ceci : IP & MASQUE.</p>
<h4>L'opération &</h4>
<p>Revoie 1 si les deux paramètres valent 1.</p>
<p>0 & 0 = 0<br>0 & 1 = 0<br>1 & 0 = 0<br>1 & 1 = 1</p>
<h4>Exemple :</h4>
<p>IP = 172.22.66.18<br>MASQUE = 255.255.252.0</p>
<pre>  10101100.00011110.01000010.00010010<br>& 11111111.11111111.11111100.00000000<br>= 10101100.00011110.01000000.00000000</pre>
<p>NET_ID = 172.22.0.0<br>SUBNET_ID = 172.22.64.0</p>

// src/views/network/StructureIp.vue
<template>
	<div>
		<h1>Structure d'une adresse IP</h1>

		<p style="text-align: center;"><span style="background-color: lightgray;"><strong><span style="color: red;">[ NET_ID ]</span>&nbsp;<span style="color: blue;">[ HOST_ID ]</span></strong></span></p>
		<p style="text-align: center;">Classe A: <span style="background-color: lightgray;"><strong><span style="color: red;">x</span>.<span style="color: blue;">x.x.x</span></strong></span></p>
		<p style="text-align: center;">Classe B: <span style="background-color: lightgray;"><strong><span style="color: red;">x.x</span>.<span style="color: blue;">x.x</span></strong></span></p>
		<p style="text-align: center;">Classe C: <span style="background-color: lightgray;"><strong><span style="color: red;">x.x.x</span>.<span style="color: blue;">x</span></strong></span></p>
		<hr>
		<p style="text-align: center;"><span style="background-color: lightgray;"><strong><span style="color: red;">[ NET_ID ]</span>&nbsp;<span style="color: green;">[ SUBNET_ID ]</span>&nbsp;<span style="color: blue;">[ HOST_ID ]</span></strong></span></p>
		<p>S'il y a un sous-réseau, le SUBNET_ID ce calcul comme ceci : IP & MASQUE.</p>
		<h4>L'opération &</h4>
		<p>Revoie 1 si les deux paramètres valent 1.</p>
		<p>0 & 0 = 0<br>0 & 1 = 0<br>1 & 0 = 0<br>1 & 1 = 1</p>
		<h4>Exemple :</h4>
		<p>IP = 172.22.66.18<br>MASQUE = 255.255.252.0</p>
		<pre>  10101100.00011110.01000010.00010010<br>& 11111111.11111111.11111100.00000000<br>= 10101100.00011110.01000000.00000000</pre>
		<p>NET_ID = 172.22.0.0<br>SUBNET_ID = 172.22.64.0</p>
	</div>
</template>

<script>
	export default {
		name: 'StructureIp',
	}
</script>
