// src/app/server-module/components/mmc/mmc.component.ts
import { Title } from "@angular/platform-browser";
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-mmc',
  templateUrl: './mmc.component.html',
  styleUrls: ['./mmc.component.css']
})
export class MmcComponent implements OnInit {

  constructor(private _titleService: Title) {
    this._titleService.setTitle("MMC");
  }

  ngOnInit(): void {
  }

}

<h1>Astuce : MMC</h1>
<p>MMC (Microsoft Management Console) est un outil permettant de simplifier l'accès aux différents outils du système.</p>

<span>Win+R, taper "mmc", appuyer sur ok</span><br>
<a href="/medias/server/mmc-1.png" target="_blank"><img src="/medias/server/mmc-1.png" alt="Step 1" class="thumb"></a>

<br><br>
<span>Ctrl+M ou fichier -> Ajouter/Supprimer un composant logiciel enfichable...</span><br>
<a href="/medias/server/mmc-2.png" target="_blank"><img src="/medias/server/mmc-2.png" alt="Step 2" class="thumb"></a>
<br><br>

<span>Sélectionner le DNS et l'ajouter</span><br>
<a href="/medias/server/mmc-3.png" target="_blank"><img src="/medias/server/mmc-3.png" alt="Step 3" class="thumb"></a>
<br><br>

<span>La même pour l'AD (Dernier élément de la liste pour gerer les OU, Utilisateurs, Computers etc)</span><br>
<a href="/medias/server/mmc-4.png" target="_blank"><img src="/medias/server/mmc-4.png" alt="Step 4" class="thumb"></a>
<br><br>

<span>Résultat :</span><br>
<a href="/medias/server/mmc-5.png" target="_blank"><img src="/medias/server/mmc-5.png" alt="Step 5" class="thumb"></a>
<br><br>

<span>Fichier -> Enregistrer sous...</span><br>
<a href="/medias/server/mmc-6.png" target="_blank"><img src="/medias/server/mmc-6.png" alt="Step 6" class="thumb"></a>
<br><br>

<p>Et la console est prête à être réutilisée.</p>
<span>⚠ Après chaque utilisation, ne pas oublier de sauvegarder ce que vous avez fait dans la console avec Ctrl+S avant de fermer la console.</span>
<br><br>
<i class="h5">Merci à JackTrash pour cette petite astuce. Retrouvez son site ici : <a href="https://epsic.jacktrash.ch" target="_blank">https://epsic.jacktrash.ch</a></i>
<br><br>

// src/views/server/Mmc.vue
<template>
  <div>
    <h1>Astuce : MMC</h1>
    <p>
      MMC (Microsoft Management Console) est un outil permettant de simplifier
      l'accès aux différents outils du système.
    </p>

    <span>Win+R, taper "mmc", appuyer sur ok</span><br />
    <a href="/medias/server/mmc-1.png" target="_blank"
      ><img src="/medias/server/mmc-1.png" alt="Step 1" class="thumb"
    /></a>

    <br /><br />
    <span
      >Ctrl+M ou fichier -> Ajouter/Supprimer un composant logiciel
      enfichable...</span
    ><br />
    <a href="/medias/server/mmc-2.png" target="_blank"
      ><img src="/medias/server/mmc-2.png" alt="Step 2" class="thumb"
    /></a>
    <br /><br />

    <span>Sélectionner le DNS et l'ajouter</span><br />
    <a href="/medias/server/mmc-3.png" target="_blank"
      ><img src="/medias/server/mmc-3.png" alt="Step 3" class="thumb"
    /></a>
    <br /><br />

    <span
      >La même pour l'AD (Dernier élément de la liste pour gerer les OU,
      Utilisateurs, Computers etc)</span
    ><br />
    <a href="/medias/server/mmc-4.png" target="_blank"
      ><img src="/medias/server/mmc-4.png" alt="Step 4" class="thumb"
    /></a>
    <br /><br />

    <span>Résultat :</span><br />
    <a href="/medias/server/mmc-5.png" target="_blank"
      ><img src="/medias/server/mmc-5.png" alt="Step 5" class="thumb"
    /></a>
    <br /><br />

    <span>Fichier -> Enregistrer sous...</span><br />
    <a href="/medias/server/mmc-6.png" target="_blank"
      ><img src="/medias/server/mmc-6.png" alt="Step 6" class="thumb"
    /></a>
    <br /><br />

    <p>Et la console est prête à être réutilisée.</p>
    <span
      >⚠ Après chaque utilisation, ne pas oublier de sauvegarder ce que vous
      avez fait dans la console avec Ctrl+S avant de fermer la console.</span
    >
    <br /><br />
    <i class="h5"
      >Merci à JackTrash pour cette petite astuce. Retrouvez son site ici :
      <a href="https://epsic.jacktrash.ch" target="_blank"
        >https://epsic.jacktrash.ch</a
      ></i
    >
    <br /><br />
  </div>
</template>

<style scoped>
img.thumb {
  max-width: 50%;
}
</style>

<script>
export default {
  name: "Mmc",
}
</script>
