// src/modules/java/views/Operateurs.vue
<script setup>
import ShowCode from "@/components/ShowCode.vue"
</script>

<template>
  <div>
    <h2>Changer la valeur d'une variable</h2>
    <p>
      On utilise le signe <code>=</code> pour donner une nouvelle valeur à une
      variable.
    </p>
    <ShowCode raw="maVariable = 5;" lang="java" />

    <h2>Effectuer un calcul</h2>
    <p>Il existe 5 opérations de bases :</p>
    <table class="mx-auto">
      <thead>
        <tr>
          <th>Symbole</th>
          <th>Nom</th>
          <th>Exemple</th>
          <th>Remarque</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>+</td>
          <td>Addition</td>
          <td>
            <ShowCode raw="maVar = 3 + 4; // maVar vaut 7" lang="java" />
          </td>
          <td></td>
        </tr>
        <tr>
          <td>-</td>
          <td>Soustraction</td>
          <td>
            <ShowCode raw="maVar = 10 - 4; // maVar vaut 6" lang="java" />
          </td>
          <td></td>
        </tr>
        <tr>
          <td>*</td>
          <td>Multiplication</td>
          <td>
            <ShowCode raw="maVar = 3 * 3; // maVar vaut 9" lang="java" />
          </td>
          <td></td>
        </tr>
        <tr>
          <td>/</td>
          <td>Division</td>
          <td>
            <ShowCode
              raw="maVar = 20 / 4; // maVar vaut 5&NewLine;maVar = 20 / 3; // maVar vaut 6"
              lang="java"
            />
          </td>
          <td>
            Si les deux nombres sont des entiers (<code>byte</code>,
            <code>short</code>, <code>int</code> ou <code>long</code>), alors le
            résultat sera aussi un nombre entier (arrondi inférieur).
          </td>
        </tr>
        <tr>
          <td>%</td>
          <td>Modulo</td>
          <td>
            <ShowCode raw="maVar = 42 % 10; // maVar vaut 2" lang="java" />
          </td>
          <td>Renvoie le reste de la division.</td>
        </tr>
      </tbody>
    </table>

    <h2>Effectuer un calcul complexe</h2>
    <p>Vous pouvez mettre plus d'un opérateur par ligne :</p>
    <ShowCode raw="maVar = 2 + 3 + 4; // maVar vaut 9" lang="java" />
    <p>
      Attention cependant à la priorité des opérations. Vous pouvez mettre des
      parenthèses comme en mathématique.
    </p>
    <ShowCode
      raw="maVar = 2 + 3 * 5; // maVar vaut 17&NewLine;maVar = (2 + 3) * 5; // maVar vaut 25"
      lang="java"
    />

    <h2>Raccourci de programmation</h2>
    <p>
      C'est bien connu, les programmeurs sont flemmards. Il existe donc des
      écritures raccourcies pour certaines opérations :
    </p>
    <table class="mx-auto">
      <thead>
        <tr>
          <th>Symbole</th>
          <th>Avant</th>
          <th>Après</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>+=</td>
          <td>
            <ShowCode raw="maVar = maVar + 10;" lang="java" />
          </td>
          <td>
            <ShowCode raw="maVar += 10;" lang="java" />
          </td>
        </tr>
        <tr>
          <td>-=</td>
          <td>
            <ShowCode raw="maVar = maVar - 10;" lang="java" />
          </td>
          <td>
            <ShowCode raw="maVar -= 10;" lang="java" />
          </td>
        </tr>
        <tr>
          <td>*=</td>
          <td>
            <ShowCode raw="maVar = maVar * 2;" lang="java" />
          </td>
          <td>
            <ShowCode raw="maVar *= 2;" lang="java" />
          </td>
        </tr>
        <tr>
          <td>/=</td>
          <td>
            <ShowCode raw="maVar = maVar / 2;" lang="java" />
          </td>
          <td>
            <ShowCode raw="maVar /= 2;" lang="java" />
          </td>
        </tr>
        <tr>
          <td>%=</td>
          <td>
            <ShowCode raw="maVar = maVar % 5;" lang="java" />
          </td>
          <td>
            <ShowCode raw="maVar %= 5;" lang="java" />
          </td>
        </tr>
        <tr>
          <td>++</td>
          <td>
            <ShowCode raw="maVar += 1;" lang="java" />
          </td>
          <td>
            <ShowCode raw="maVar++;" lang="java" />
          </td>
        </tr>
        <tr>
          <td>--</td>
          <td>
            <ShowCode raw="maVar -= 1;" lang="java" />
          </td>
          <td>
            <ShowCode raw="maVar--;" lang="java" />
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// angular/epsic-burkhalter-dev/src/app/java-module/components/operateurs/operateurs.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";
import 'prismjs/components/prism-java';

declare var Prism: any;

@Component({
  selector: 'app-operateurs',
  templateUrl: './operateurs.component.html',
  styleUrls: ['./operateurs.component.css']
})
export class OperateursComponent implements OnInit {

  public Prism: any = {};

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Les opérateurs");
    this.Prism = Prism;
  }

  ngOnInit(): void {
  }

}

<h1>Les opérateurs</h1>

<h3>Changer la valeur d'une variable</h3>
<p>On utilise le signe = pour donner une nouvelle valeur à une variable.</p>
<pre class="language-java"><app-code inlineCode="maVariable = 5;" [lang]="Prism.languages.java"></app-code></pre>

<h3>Effectuer un calcul</h3>
<p>Il existe 5 opérations de bases :</p>
<table class="table">
	<thead>
		<tr>
			<th>Symbole</th>
			<th>Nom</th>
			<th>Exemple</th>
			<th>Remarque</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>+</td>
			<td>Addition</td>
			<td><pre class="language-java"><app-code inlineCode="maVar = 3 + 4; //maVar vaut 7" [lang]="Prism.languages.java"></app-code></pre></td>
			<td></td>
		</tr>
		<tr>
			<td>-</td>
			<td>Soustraction</td>
			<td><pre class="language-java"><app-code inlineCode="maVar = 10 - 4; //maVar vaut 6" [lang]="Prism.languages.java"></app-code></pre></td>
			<td></td>
		</tr>
		<tr>
			<td>*</td>
			<td>Multiplication</td>
			<td><pre class="language-java"><app-code inlineCode="maVar = 3 * 3; //maVar vaut 9" [lang]="Prism.languages.java"></app-code></pre></td>
			<td></td>
		</tr>
		<tr>
			<td>/</td>
			<td>Division</td>
			<td><pre class="language-java"><app-code inlineCode="maVar = 20 / 4; //maVar vaut 5
maVar = 20 / 3; //maVar vaut 6" [lang]="Prism.languages.java"></app-code></pre></td>
			<td>Si les deux nombres sont des entiers (byte, short, int ou long), alors le résultat sera aussi un nombre entier. Arrondi inférieur.</td>
		</tr>
		<tr>
			<td>%</td>
			<td>Modulo</td>
			<td><pre class="language-java"><app-code inlineCode="maVar = 42 % 10; //maVar vaut 2" [lang]="Prism.languages.java"></app-code></pre></td>
			<td>Renvoie le reste de la division.</td>
		</tr>
	</tbody>
</table>

<h3>Effectuer un calcul complexe</h3>
<p>Vous pouvez mettre plus d'un opérateur par calcul :<p>
<pre class="language-java"><app-code inlineCode="maVar = 2 + 3 + 4; //maVar vaut 9" [lang]="Prism.languages.java"></app-code></pre>
<p>Attention cependant à la priorité des opérations. Vous pouvez mettre des parenthèses comme en mathématique.<p>
<pre class="language-java"><app-code inlineCode="maVar = 2 + 3 * 5; //maVar vaut 17
maVar = (2 + 3) * 5; //maVar vaut 25" [lang]="Prism.languages.java"></app-code></pre>

<h3>Raccourci de programmation</h3>
<p>C'est bien connu, les programmeurs sont des flemmards, il existe donc des écritures raccourcies pour certaines opérations :</p>
<table class="table">
	<thead>
		<tr>
			<th>Symbole</th>
			<th>Avant</th>
			<th>Après</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>+=</td>
			<td><pre class="language-java"><app-code inlineCode="maVar = maVar + 10;" [lang]="Prism.languages.java"></app-code></pre></td>
			<td><pre class="language-java"><app-code inlineCode="maVar += 10;" [lang]="Prism.languages.java"></app-code></pre></td>
		</tr>
		<tr>
			<td>-=</td>
			<td><pre class="language-java"><app-code inlineCode="maVar = maVar - 10;" [lang]="Prism.languages.java"></app-code></pre></td>
			<td><pre class="language-java"><app-code inlineCode="maVar -= 10;" [lang]="Prism.languages.java"></app-code></pre></td>
		<tr>
			<td>*=</td>
			<td><pre class="language-java"><app-code inlineCode="maVar = maVar * 2;" [lang]="Prism.languages.java"></app-code></pre></td>
			<td><pre class="language-java"><app-code inlineCode="maVar *= 2;" [lang]="Prism.languages.java"></app-code></pre></td>
		</tr>
		<tr>
			<td>/=</td>
			<td><pre class="language-java"><app-code inlineCode="maVar = maVar / 2;" [lang]="Prism.languages.java"></app-code></pre></td>
			<td><pre class="language-java"><app-code inlineCode="maVar /= 2;" [lang]="Prism.languages.java"></app-code></pre></td>
		</tr>
		<tr>
			<td>%=</td>
			<td><pre class="language-java"><app-code inlineCode="maVar = maVar % 5;" [lang]="Prism.languages.java"></app-code></pre></td>
			<td><pre class="language-java"><app-code inlineCode="maVar %= 5;" [lang]="Prism.languages.java"></app-code></pre></td>
		</tr>
		<tr>
			<td>++</td>
			<td><pre class="language-java"><app-code inlineCode="maVar += 1;" [lang]="Prism.languages.java"></app-code></pre></td>
			<td><pre class="language-java"><app-code inlineCode="maVar++;" [lang]="Prism.languages.java"></app-code></pre></td>
		</tr>
		<tr>
			<td>--</td>
			<td><pre class="language-java"><app-code inlineCode="maVar -= 1;" [lang]="Prism.languages.java"></app-code></pre></td>
			<td><pre class="language-java"><app-code inlineCode="maVar--;" [lang]="Prism.languages.java"></app-code></pre></td>
		<tr>
	</tbody>
</table>
