// src/app/tools-module/components/password-generator/password-generator.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";

@Component({
  selector: 'app-password-generator',
  templateUrl: './password-generator.component.html',
  styleUrls: ['./password-generator.component.css']
})
export class PasswordGeneratorComponent implements OnInit {

  private readonly lower: string = 'abcdefghijklmnopqrstuvwxyz';
  private readonly upper: string = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  private readonly numbers: string = '0123456789';
  private readonly symbols: string = '!#$%&*+-=?@';
  public readonly similar: string = '1lIioO0';

  public length: number = 12;
  public useLower: boolean = true;
  public useUpper: boolean = true;
  public useNumbers: boolean = true;
  public useSymbols: boolean = true;
  public avoidSimilar: boolean = true;

  public history: string[] = [];

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Générateur de mot de passes");
  }

  ngOnInit(): void {
  }

  public generate(): void {
    let characters = '';

    if(this.useLower){
      characters += this.lower;
    }
    if(this.useUpper){
      characters += this.upper;
    }
    if(this.useNumbers){
      characters += this.numbers;
    }
    if(this.useSymbols){
      characters += this.symbols;
    }
    if(this.avoidSimilar){
      for (let i = 0; i < this.similar.length; i++) {
        characters = characters.replace(this.similar.charAt(i), '');
      }
    }

    let password = '';
    let charactersLength = characters.length;
    for (let i = 0; i < this.length; i++) {
      password += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    this.history.unshift(password);
  }

}

<h1>Générateur de mot de passes</h1>
<strong>Longeur du mot de passe :</strong><br>
<input type="range" min="4" max="32" [(ngModel)]="length"><br>
<input type="number" [(ngModel)]="length">&nbsp;<span title="Pour une longueur supérieure à 32, utiliser ce champ">🛈</span><br>
<input type="checkbox" id="useLower" [(ngModel)]="useLower">&nbsp;<label for="useLower">Minuscules</label><br>
<input type="checkbox" id="useUpper" [(ngModel)]="useUpper">&nbsp;<label for="useUpper">Majuscules</label><br>
<input type="checkbox" id="useNumbers" [(ngModel)]="useNumbers">&nbsp;<label for="useNumbers">Chiffres</label><br>
<input type="checkbox" id="useSymbols" [(ngModel)]="useSymbols">&nbsp;<label for="useSymbols">Symboles</label><br>
<input type="checkbox" id="avoidSimilar" [(ngModel)]="avoidSimilar">&nbsp;<label for="avoidSimilar">Exclure les caractères similaires ({{ similar.split('').join(' ') }})</label><br>

<button class="btn btn-primary" (click)="generate()">Générer</button>

<samp>{{ history[0] }}</samp>

<details>
	<summary>Historique</summary>
	<ul>
		<li *ngFor="let password of history">{{ password }}</li>
	</ul>
</details>

// src/modules/tools/views/PasswordGenerator.vue
<script setup>
import { ref } from "vue"

const LOWER = "abcdefghijklmnopqrstuvwxyz",
  UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  NUMBERS = "0123456789",
  SYMBOLS = "!#$%&*+-=?@",
  SIMILAR = "1lIioO0"

const length = ref(12)
const useLower = ref(true)
const useUpper = ref(true)
const useNumbers = ref(true)
const useSymbols = ref(true)
const avoidSimilar = ref(true)
const history = ref([])

const generate = () => {
  let characters = ""

  if (useLower.value) characters += LOWER
  if (useUpper.value) characters += UPPER
  if (useNumbers.value) characters += NUMBERS
  if (useSymbols.value) characters += SYMBOLS

  if (avoidSimilar.value) {
    for (let i = 0; i < SIMILAR.length; i++) {
      characters = characters.replace(SIMILAR.charAt(i), "")
    }
  }

  let password = ""
  let charactersLength = characters.length
  for (let i = 0; i < length.value; i++) {
    password += characters.charAt(Math.floor(Math.random() * charactersLength))
  }
  history.value.unshift(password)
}
</script>

<template>
  <div class="flex flex-col">
    <div class="flex flex-wrap sm:flex-row gap-y-1 gap-x-12">
      <strong>Longeur du mot de passe :</strong>
      <div class="flex gap-1 sm:order-last">
        <span
          title="Pour une longueur supérieure à 32, utiliser le champ texte."
          class="text-blue-500"
          >🛈</span
        >
        <input type="number" v-model="length" class="border w-16" />
      </div>
      <input type="range" min="4" max="32" v-model="length" />
    </div>
    <div class="flex gap-1">
      <input type="checkbox" id="useLower" v-model="useLower" />
      <label for="useLower">Minuscules</label>
    </div>
    <div class="flex gap-1">
      <input type="checkbox" id="useUpper" v-model="useUpper" />
      <label for="useUpper">Majuscules</label>
    </div>
    <div class="flex gap-1">
      <input type="checkbox" id="useNumbers" v-model="useNumbers" />
      <label for="useNumbers">Chiffres</label>
    </div>
    <div class="flex gap-1">
      <input type="checkbox" id="useSymbols" v-model="useSymbols" />
      <label for="useSymbols">Symboles</label>
    </div>
    <div class="flex gap-1">
      <input type="checkbox" id="avoidSimilar" v-model="avoidSimilar" />
      <label for="avoidSimilar"
        >Exclure les caractères similaires ({{
          SIMILAR.split("").join(" ")
        }})</label
      >
    </div>

    <button
      class="mx-auto w-min my-5 px-3 py-2 text-white bg-blue-500 hover:bg-blue-600 rounded-lg"
      @click="generate()"
    >
      Générer
    </button>
    <samp class="text-center">{{ history[0] }}</samp>

    <details>
      <summary>Historique</summary>
      <ul>
        <li v-for="password of history" :key="password">{{ password }}</li>
      </ul>
    </details>

    <div class="alert-danger text-start">
      <h3 class="inline alert-title">DON'T TRUST, VERIFY</h3>
      <div>
        Les mots de passe sont générés uniquement par votre navigateur et ne
        parviennent jamais au serveur. Vous être libre de vérifier cela par
        vous-même depuis le
        <a
          target="_blank"
          href="https://github.com/BurkhalterY/epsic.burkhalter.dev/blob/vue3/src/modules/tools/views/PasswordGenerator.vue"
          >code source</a
        >. <strong>Néanmoins</strong>, cet outil n'est pas une solution
        certifiée et ne devrait pas être utilisé pour générer des mots de passe
        destinés à protéger des éléments critiques !
      </div>
    </div>
  </div>
</template>
