// src/modules/java/views/Structogramme.vue
<script setup>
import ShowCode from "@/components/ShowCode.vue"
</script>

<template>
  <div>
    <p>Une petite liste des symboles Nassi-Shneidermann.</p>
    <table class="mx-auto">
      <thead>
        <tr>
          <th>Symbole</th>
          <th>Code</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><img src="/java/medias/nassi-main.png" alt="main" /></td>
          <td>
            <ShowCode file="/java/code/nassi-main.java" lang="java" />
          </td>
        </tr>
        <tr>
          <td>
            <img src="/java/medias/nassi-instruction.png" alt="instruction" />
          </td>
          <td>
            <ShowCode file="/java/code/nassi-instruction.java" lang="java" />
          </td>
        </tr>
        <tr>
          <td><img src="/java/medias/nassi-if.png" alt="if" /></td>
          <td>
            <ShowCode file="/java/code/nassi-if.java" lang="java" />
          </td>
        </tr>
        <tr>
          <td><img src="/java/medias/nassi-switch.png" alt="if" /></td>
          <td>
            <ShowCode file="/java/code/nassi-switch.java" lang="java" />
          </td>
        </tr>
        <tr>
          <td><img src="/java/medias/nassi-while.png" alt="while" /></td>
          <td>
            <ShowCode file="/java/code/nassi-while.java" lang="java" />
          </td>
        </tr>
        <tr>
          <td><img src="/java/medias/nassi-do-while.png" alt="dpo while" /></td>
          <td>
            <ShowCode file="/java/code/nassi-do-while.java" lang="java" />
          </td>
        </tr>
        <tr>
          <td><img src="/java/medias/nassi-for.png" alt="for" /></td>
          <td>
            <ShowCode file="/java/code/nassi-for.java" lang="java" />
          </td>
        </tr>
        <tr>
          <td><img src="/java/medias/nassi-methode-appel.png" alt="for" /></td>
          <td>
            <ShowCode file="/java/code/nassi-methode-appel.java" lang="java" />
          </td>
        </tr>
        <tr>
          <td>
            <img src="/java/medias/nassi-methode-declaration.png" alt="for" />
          </td>
          <td>
            <ShowCode
              file="/java/code/nassi-methode-declaration.java"
              lang="java"
            />
            <p>Attention : ce code s'écrit en dehors de la fonction main()</p>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// src/app/java-module/components/structogramme/structogramme.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";
import 'prismjs/components/prism-java';

declare var Prism: any;

@Component({
  selector: 'app-structogramme',
  templateUrl: './structogramme.component.html',
  styleUrls: ['./structogramme.component.css']
})
export class StructogrammeComponent implements OnInit {

  public Prism: any = {};

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Symboles Nassi-Shneidermann");
    this.Prism = Prism;
  }

  ngOnInit(): void {
  }

}

<h1>Symboles Nassi-Shneidermann</h1>
<p>Une petite liste des symboles Nassi-Shneidermann :</p>
<table class="table">
	<thead>
		<tr>
			<th>Symbole</th>
			<th>Code</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><img src="medias/java/nassi-main.png" alt="main" /></td>
			<td><pre class="language-java"><app-code file="java/nassi-main.java" [lang]="Prism.languages.java"></app-code></pre></td>
		</tr>
		<tr>
			<td><img src="medias/java/nassi-instruction.png" alt="instruction" /></td>
			<td><pre class="language-java"><app-code file="java/nassi-instruction.java" [lang]="Prism.languages.java"></app-code></pre></td>
		</tr>
		<tr>
			<td><img src="medias/java/nassi-if.png" alt="if" /></td>
			<td><pre class="language-java"><app-code file="java/nassi-if.java" [lang]="Prism.languages.java"></app-code></pre></td>
		</tr>
		<tr>
			<td><img src="medias/java/nassi-switch.png" alt="if" /></td>
			<td><pre class="language-java"><app-code file="java/nassi-switch.java" [lang]="Prism.languages.java"></app-code></pre></td>
		</tr>
		<tr>
			<td><img src="medias/java/nassi-while.png" alt="while" /></td>
			<td><pre class="language-java"><app-code file="java/nassi-while.java" [lang]="Prism.languages.java"></app-code></pre></td>
		</tr>
		<tr>
			<td><img src="medias/java/nassi-do-while.png" alt="dpo while" /></td>
			<td><pre class="language-java"><app-code file="java/nassi-do-while.java" [lang]="Prism.languages.java"></app-code></pre></td>
		</tr>
		<tr>
			<td><img src="medias/java/nassi-for.png" alt="for" /></td>
			<td><pre class="language-java"><app-code file="java/nassi-for.java" [lang]="Prism.languages.java"></app-code></pre></td>
		</tr>
		<tr>
			<td><img src="medias/java/nassi-methode-appel.png" alt="for" /></td>
			<td><pre class="language-java"><app-code file="java/nassi-methode-appel.java" [lang]="Prism.languages.java"></app-code></pre></td>
		</tr>
		<tr>
			<td><img src="medias/java/nassi-methode-declaration.png" alt="for" /></td>
			<td><pre class="language-java"><app-code file="java/nassi-methode-declaration.java" [lang]="Prism.languages.java"></app-code></pre><p>Attention : ce code s'écrit en dehors de la fonction main()</p></td>
		</tr>
	</tbody>
</table>
