// src/app/java-module/components/new/new.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";
import 'prismjs/components/prism-java';

declare var Prism: any;

@Component({
  selector: 'app-new',
  templateUrl: './new.component.html',
  styleUrls: ['./new.component.css']
})
export class NewComponent implements OnInit {

  public Prism: any = {};

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Créer un nouveau projet");
    this.Prism = Prism;
  }

  ngOnInit(): void {
  }

}

<h1>Créer un nouveau projet</h1>
<ol>
	<li>Ouvrez NetBeans.</li>
	<li>Cliquez sur Nouveau projet en haut à gauche.</li>
	<img src="/medias/java/new1.png" alt="étape 1" />
	<li>Sélectionnez Java, puis Java Application.</li>
	<img src="/medias/java/new2.png" alt="étape 2" />
	<li>Nommez votre programme et choisissez son emplacement.</li>
	<img src="/medias/java/new3.png" alt="étape 3" />
	<li>Votre programme devrait ressembler à ça :</li>
	<pre class="language-java"><app-code file="java/new-project.java" [lang]="Prism.languages.java"></app-code></pre>
	<li>Vous pouvez alors supprimer tous les commentaires inutiles.</li>
	<pre class="language-java"><app-code file="java/new-project-no-commentary.java" [lang]="Prism.languages.java"></app-code></pre>
</ol>

// src/views/java/New.vue
<template>
	<div>
		<h1>Créer un nouveau projet</h1>
		<ol>
			<li>Ouvrez NetBeans.</li>
			<li>Cliquez sur Nouveau projet en haut à gauche.</li>
			<img src="/medias/java/new1.png" alt="étape 1" />
			<li>Sélectionnez Java, puis Java Application.</li>
			<img src="/medias/java/new2.png" alt="étape 2" />
			<li>Nommez votre programme et choisissez son emplacement.</li>
			<img src="/medias/java/new3.png" alt="étape 3" />
			<li>Votre programme devrait ressembler à ça :</li>
			<pre class="language-java"><ShowCode file="java/new-project.java" lang="java"/></pre>
			<li>Vous pouvez alors supprimer tous les commentaires inutiles.</li>
			<pre class="language-java"><ShowCode file="java/new-project-no-commentary.java" lang="java"/></pre>
		</ol>
	</div>
</template>

<script>
	import ShowCode from '../../components/ShowCode.vue'

	export default {
		name: 'New',
		components: {
			ShowCode,
		},
	}
</script>
