// src/views/poo/Fenetre.vue
<template>
	<div>
		<h1>Première fenêtre</h1>
		<p>Pour créer une fenêtre en Java, il faut créer une nouvelle classe héritée de la classe JFrame. JFrame est une classe permettant d'afficher une fenêtre et d'y configurer pas mal d'options.</p>
		<p>Notre classe Fenetre :</p>
		<pre class="language-java"><ShowCode file="poo/fenetre0.java" lang="java"/></pre>
		<p>Et la classe principale dans laquelle nous instancions cette Fenetre :</p>
		<pre class="language-java"><ShowCode file="poo/fenetre1.java" lang="java"/></pre>
		<p>Lancez le programme, une fenêtre vide devrait apparaitre au milieu de l'écran :</p>
		<img src="/medias/poo/fenetre.png" alt="Fenêtre de 600x800" />
	</div>
</template>

<script>
	import ShowCode from '../../components/ShowCode.vue'

	export default {
		name: 'Fenetre',
		components: {
			ShowCode,
		},
	}
</script>

// angular/epsic-burkhalter-dev/src/app/poo/components/fenetre/fenetre.component.ts
import { Component, OnInit } from '@angular/core';
import 'prismjs';
import 'prismjs/components/prism-java';

declare var Prism: any;

@Component({
  selector: 'app-fenetre',
  templateUrl: './fenetre.component.html',
  styleUrls: ['./fenetre.component.css']
})
export class FenetreComponent implements OnInit {

  public fenetre: string[] = new Array(2).fill('');

  constructor() { }

  ngOnInit(): void {
    for(let i = 0; i < this.fenetre.length; i++){
      fetch(`/assets/code/poo/fenetre${i}.java`)
      .then(response => response.text())
      .then(data => {
        this.fenetre[i] = Prism.highlight(data, Prism.languages.java);
      });
    }
  }

}

<h1>Première fenêtre</h1>
<p>Pour créer une fenêtre en Java, il faut créer une nouvelle classe héritée de la classe JFrame. JFrame est une classe permettant d'afficher une fenêtre et d'y configurer pas mal d'options.</p>
<p>Notre classe Fenetre :</p>
<pre class="language-java"><code [innerHTML]="fenetre[0]"></code></pre>
<p>Et la classe principale dans laquelle nous instancions cette Fenetre :</p>
<pre class="language-java"><code [innerHTML]="fenetre[1]"></code></pre>
<p>Lancez le programme, une fenêtre vide devrait apparaitre au milieu de l'écran :</p>
<img src="/medias/poo/fenetre.png" alt="Fenêtre de 600x800" />
