// src/views/poo/Constructeur.vue
<template>
	<div>
		<h1>Les constructeurs</h1>
		<p>Les constructeurs servent à initialiser l'objet lors de l'instanciation. Ce sont simplement des méthodes qui ont le même nom que la classe. Attention, ces méthodes n'ont pas de type de retour, même pas void. Exemple :</p>
		<pre class="language-java"><ShowCode file="poo/constructeur0.java" lang="java"/></pre>
		<p>Rappelez-vous qu'il est possible d'avoir plusieurs méthodes avec le même nom si les arguments sont différents. Java choisira tous seul en fonction des arguments passés. Ceci s'appelle la surcharge d'une méthode.</p>
		<p>Je peux maintenant instancier mon objet :</p>
		<pre class="language-java"><ShowCode file="poo/constructeur1.java" lang="java"/></pre>
	</div>
</template>

<script>
	import ShowCode from '../../components/ShowCode.vue'

	export default {
		name: 'Constructeur',
		components: {
			ShowCode,
		},
	}
</script>

// angular/epsic-burkhalter-dev/src/app/poo/components/constructeur/constructeur.component.ts
import { Component, OnInit } from '@angular/core';
import 'prismjs';
import 'prismjs/components/prism-java';

declare var Prism: any;

@Component({
  selector: 'app-constructeur',
  templateUrl: './constructeur.component.html',
  styleUrls: ['./constructeur.component.css']
})
export class ConstructeurComponent implements OnInit {

  public constructeur: string[] = new Array(2).fill('');

  constructor() { }

  ngOnInit(): void {
    for(let i = 0; i < this.constructeur.length; i++){
      fetch(`/assets/code/poo/constructeur${i}.java`)
      .then(response => response.text())
      .then(data => {
        this.constructeur[i] = Prism.highlight(data, Prism.languages.java);
      });
    }
  }

}

<h1>Les constructeurs</h1>
<p>Les constructeurs servent à initialiser l'objet lors de l'instanciation. Ce sont simplement des méthodes qui ont le même nom que la classe. Attention, ces méthodes n'ont pas de type de retour, même pas void. Exemple :</p>
<pre class="language-java"><code [innerHTML]="constructeur[0]"></code></pre>
<p>Rappelez-vous qu'il est possible d'avoir plusieurs méthodes avec le même nom si les arguments sont différents. Java choisira tous seul en fonction des arguments passés. Ceci s'appelle la surcharge d'une méthode.</p>
<p>Je peux maintenant instancier mon objet :</p>
<pre class="language-java"><code [innerHTML]="constructeur[1]"></code></pre>
