// src/views/java/ConversionBoucle.vue
<template>
	<div>
		<h1>Conversion d'un for en while et inversement</h1>
		<p>Voici deux codes qui font exactement la même chose :</p>
		<table class="table">
			<thead>
				<tr>
					<th>Boucle for</th>
					<th>Boucle while</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><pre class="language-java"><ShowCode file="java/conv-for.java" lang="java"/></pre></td>
					<td><pre class="language-java"><ShowCode file="java/conv-while.java" lang="java"/></pre></td>
				</tr>
			</tbody>
		</table>
	</div>
</template>

<script>
	import ShowCode from '../../components/ShowCode.vue'

	export default {
		name: 'ConversionBoucle',
		components: {
			ShowCode,
		},
	}
</script>

// angular/epsic-burkhalter-dev/src/app/java-module/components/conversion-boucle/conversion-boucle.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";
import 'prismjs/components/prism-java';

declare var Prism: any;

@Component({
  selector: 'app-conversion-boucle',
  templateUrl: './conversion-boucle.component.html',
  styleUrls: ['./conversion-boucle.component.css']
})
export class ConversionBoucleComponent implements OnInit {

  public Prism: any = {};

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Conversion d'un for en while et inversement");
    this.Prism = Prism;
  }

  ngOnInit(): void {
  }

}

<h1>Conversion d'un for en while et inversement</h1>
<p>Voici deux codes qui font exactement la même chose :</p>
<table class="table">
	<thead>
		<tr>
			<th>Boucle for</th>
			<th>Boucle while</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><pre class="language-java"><app-code file="java/conv-for.java" [lang]="Prism.languages.java"></app-code></pre></td>
			<td><pre class="language-java"><app-code file="java/conv-while.java" [lang]="Prism.languages.java"></app-code></pre></td>
		</tr>
	</tbody>
</table>
