// src/views/network/Base.vue
<template>
  <div>
    <nav class="navbar navbar-expand">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <router-link class="nav-link" to="/">Accueil</router-link>
        </li>
        <li class="nav-item">
          <router-link class="nav-link" to="/network">Menu</router-link>
        </li>
      </ul>
      <span class="navbar-text">© Burkhalter Yannis</span>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <router-view />
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.navbar {
  background-color: #0f7ddf;
}

nav a {
  color: white;
}
</style>

<script>
export default {
  name: "Base",
}
</script>

// angular/epsic-burkhalter-dev/src/app/network-module/components/base/base.component.ts
import { Component, OnInit, Inject } from '@angular/core';
import { DOCUMENT } from '@angular/common';

@Component({
  selector: 'app-base',
  templateUrl: './base.component.html',
  styleUrls: ['./base.component.css']
})
export class BaseComponent implements OnInit {

  constructor(@Inject(DOCUMENT) private _document: HTMLDocument) {
    this._document.getElementById("appFavicon")!.setAttribute("href", "/assets/icon/network.ico");
  }

  ngOnInit(): void {
  }

}

<nav class="navbar navbar-expand">
	<ul class="navbar-nav mr-auto">
		<li class="nav-item"><a class="nav-link" href="" routerLink="/">Accueil</a></li>
		<li class="nav-item"><a class="nav-link" href="" routerLink="/network">Menu</a></li>
	</ul>
	<span class="navbar-text">© Burkhalter Yannis</span>
</nav>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<router-outlet></router-outlet>
		</div>
	</div>
</div>
