// src/views/poo/ClassesAbstraites.vue
<template>
  <div>
    <h1>Les classes abstraites</h1>
    <p>
      Une classe abstraite est une classe qui ne peut pas être instancié car
      certaines de ses méthodes ne sont pas définies. Son but est d'en faire
      hériter une autre classe pour surcharger ces méthodes. C'est une espèce de
      modèle de classe.
    </p>
    <p>Voici comment déclarer une classe abstraite et ses méthodes :</p>
    <pre
      class="language-java"
    ><ShowCode file="poo/classesAbstraites0.java" lang="java"/></pre>

    <h3>Exemple</h3>
    <p>Pour mieux comprendre leur fonctionnement, voici un exemple complet :</p>
    <p>
      Imaginez un programme permettant de calculer le périmètre et l'aire de
      plusieurs formes. Toutes ces formes auraient une manière différente de
      calculer le périmètre et l'aire. Si on veut les rassembler dans un tableau
      par exemple, il nous faudrait une classe parente commune et donc forcément
      abstraite.<br />Nous allons commencer avec 3 clases : Forme, Rectangle et
      Cercle.
    </p>
    <p>La classe abstraite Forme :</p>
    <pre
      class="language-java"
    ><ShowCode file="poo/classesAbstraites1.java" lang="java"/></pre>
    <p>La classe Rectangle :</p>
    <pre
      class="language-java"
    ><ShowCode file="poo/classesAbstraites2.java" lang="java"/></pre>
    <p>La classe Cercle :</p>
    <pre
      class="language-java"
    ><ShowCode file="poo/classesAbstraites3.java" lang="java"/></pre>
    <p>La classe principale :</p>
    <pre
      class="language-java"
    ><ShowCode file="poo/classesAbstraites4.java" lang="java"/></pre>
  </div>
</template>

<script>
import ShowCode from "../../components/ShowCode.vue"

export default {
  name: "ClassesAbstraites",
  components: {
    ShowCode,
  },
}
</script>

// angular/epsic-burkhalter-dev/src/app/poo/components/classes-abstraites/classes-abstraites.component.ts
import { Component, OnInit } from '@angular/core';
import 'prismjs';
import 'prismjs/components/prism-java';

declare var Prism: any;

@Component({
  selector: 'app-classes-abstraites',
  templateUrl: './classes-abstraites.component.html',
  styleUrls: ['./classes-abstraites.component.css']
})
export class ClassesAbstraitesComponent implements OnInit {

  public classesAbstraites: string[] = new Array(5).fill('');

  constructor() { }

  ngOnInit(): void {
    for(let i = 0; i < this.classesAbstraites.length; i++){
      fetch(`/assets/code/poo/classesAbstraites${i}.java`)
      .then(response => response.text())
      .then(data => {
        this.classesAbstraites[i] = Prism.highlight(data, Prism.languages.java);
      });
    }
  }

}

<h1>Les classes abstraites</h1>
<p>Une classe abstraite est une classe qui ne peut pas être instancié car certaines de ses méthodes ne sont pas définies. Son but est d'en faire hériter une autre classe pour surcharger ces méthodes. C'est une espèce de modèle de classe.</p>
<p>Voici comment déclarer une classe abstraite et ses méthodes :</p>
<pre><code class="language-java">public abstract class MaClasseAbstraite &lcub;

	// Méthodes abstraites
	public abstract void maMethode1();
	public abstract int maMethode2();
	public abstract String maMethode3();

}</code></pre>

<h3>Exemple</h3>
<p>Pour mieux comprendre leur fonctionnement, voici un exemple complet :</p>
<p>Imaginez un programme permettant de calculer le périmètre et l'aire de plusieurs formes. Toutes ces formes auraient une manière différente de calculer le périmètre et l'aire. Si on veut les rassembler dans un tableau par exemple, il nous faudrait une classe parente commune et donc forcément abstraite.<br>Nous allons commencer avec 3 clases : Forme, Rectangle et Cercle.</p>
<p>La classe abstraite Forme :</p>
<pre><code class="language-java">package testclasseabstraite;

public abstract class Forme &lcub;

	public abstract double aire();
	public abstract double perimetre();

}</code></pre>
<p>La classe Rectangle :</p>
<pre><code class="language-java">package testclasseabstraite;

public class Rectangle extends Forme &lcub;

	protected double longueur, largeur;

	public Rectangle(double longueurRect, double largeurRect)&lcub;
		this.longueur = longueurRect;
		this.largeur = largeurRect;
	}

	@Override
	public double aire() &lcub;
		return longueur * largeur;
	}

	@Override
	public double perimetre() &lcub;
		return 2*(largeur + longueur);
	}

}</code></pre>
<p>La classe Cercle :</p>
<pre><code class="language-java">package testclasseabstraite;

public class Cercle extends Forme &lcub;

	// Déclaration de la constante PI
	public static final double PI = 3.141592;

	protected double rayon;

	public Cercle(double rayon)&lcub;
		this.rayon = rayon;
	}

	@Override
	public double aire() &lcub;
		return PI * rayon * rayon;
	}

	@Override
	public double perimetre() &lcub;
		return 2 * PI * rayon;
	}
	
}</code></pre>
<p>La classe principale :</p>
<pre><code class="language-java">package testclasseabstraite;

public class TestClasseAbstraite &lcub;

	public static void main(String[] args) &lcub;
		
		Forme[] collection = new Forme[3];
		collection[0] = new Cercle(20);
		collection[1] = new Rectangle(20, 10);
		collection[2] = new Rectangle(100, 40);
		
		// Affichage de l'aire et du périmètre pour chaque forme
		for(int i = 0; i < collection.length; i++)&lcub;
			System.out.println("aire : "+collection[i].aire());
			System.out.println("perimetre : "+collection[i].perimetre());
			System.out.println();
		}

	}
}</code></pre>
