// angular/epsic-burkhalter-dev/src/app/access-module/components/valide-si/valide-si.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";

@Component({
  selector: 'app-valide-si',
  templateUrl: './valide-si.component.html',
  styleUrls: ['./valide-si.component.css']
})
export class ValideSiComponent implements OnInit {

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Valide si");
  }

  ngOnInit(): void {
  }

}

<h1>Valide si</h1>
<p>Valide si est une des propriétés des champs. Elle permet de n'autoriser à entrer que des valeurs qui correspondent à cette règle.</p>
<p>Exemples de valide si :</p>
<table class="table">
	<tr>
		<th>Valide si</th>
		<th>Description</th>
	</tr>
	<tr>
		<th colspan="2">Pour les champs Texte</th>
	</tr>
	<tr>
		<td><samp>Pas Comme "*[!a-z -]*"</samp></td>
		<td>Autorise les noms avec accents, traits d'union et espaces.</td>
	</tr>
	<tr>
		<td><samp>Comme "*@*.*"</samp></td>
		<td>Pour les e-mails. Oblige au minimum un @ et un point.</td>
	</tr>
	<tr>
		<td><samp>Comme "### ### ## ##"</samp></td>
		<td>Pour les numéros de téléphones (format: 012 345 67 89)</td>
	</tr>
	<tr>
		<td><samp>Comme "[+]## ## ### ## ##"</samp></td>
		<td>Pour les numéros de téléphones (format: +41 12 345 67 89)</td>
	</tr>
	<tr>
		<th colspan="2">Pour les champs Date/Heure</th>
	</tr>
	<tr>
		<td><samp>&lt;=Maintenant()</samp></td>
		<td>Une date qui a déjà eu lieu</td>
	</tr>
	<tr>
		<th colspan="2">Pour les champs Numérique</th>
	</tr>
	<tr>
		<td><samp>&lt;=Année(Maintenant())</samp></td>
		<td>Une année qui a déjà  eu lieu</td>
	</tr>
	<tr>
		<td><samp>&gt;=1000 Et <100000000</samp></td>
		<td>Un nombre qui a entre 4 et 8 chiffres (code PIN par exemple)</td>
	</tr>
</table>

// src/views/access/ValideSi.vue
<template>
	<div>
		<h1>Valide si</h1>
		<p>Valide si est une des propriétés des champs. Elle permet de n'autoriser à entrer que des valeurs qui correspondent à cette règle.</p>
		<p>Exemples de valide si :</p>
		<table class="table">
			<tr>
				<th>Valide si</th>
				<th>Description</th>
			</tr>
			<tr>
				<th colspan="2">Pour les champs Texte</th>
			</tr>
			<tr>
				<td><samp>Pas Comme "*[!a-z -]*"</samp></td>
				<td>Autorise les noms avec accents, traits d'union et espaces.</td>
			</tr>
			<tr>
				<td><samp>Comme "*@*.*"</samp></td>
				<td>Pour les e-mails. Oblige au minimum un @ et un point.</td>
			</tr>
			<tr>
				<td><samp>Comme "### ### ## ##"</samp></td>
				<td>Pour les numéros de téléphones (format: 012 345 67 89)</td>
			</tr>
			<tr>
				<td><samp>Comme "[+]## ## ### ## ##"</samp></td>
				<td>Pour les numéros de téléphones (format: +41 12 345 67 89)</td>
			</tr>
			<tr>
				<th colspan="2">Pour les champs Date/Heure</th>
			</tr>
			<tr>
				<td><samp>&lt;=Maintenant()</samp></td>
				<td>Une date qui a déjà eu lieu</td>
			</tr>
			<tr>
				<th colspan="2">Pour les champs Numérique</th>
			</tr>
			<tr>
				<td><samp>&lt;=Année(Maintenant())</samp></td>
				<td>Une année qui a déjà eu lieu</td>
			</tr>
			<tr>
				<td><samp>&gt;=1000 Et &lt;100000000</samp></td>
				<td>Un nombre qui a entre 4 et 8 chiffres (code PIN par exemple)</td>
			</tr>
		</table>
	</div>
</template>

<script>
	export default {
		name: 'ValideSi',
	}
</script>
