// src/modules/html/views/TypesBalises.vue
<script setup>
import ShowCode from "@/components/ShowCode.vue"
</script>

<template>
  <div>
    <p>
      Il existe deux types de balises : <strong>block</strong> et
      <strong>inline</strong>. Voici un petit tableau récapitulatif :
    </p>
    <table>
      <tr>
        <th />
        <th class="text-start">Block</th>
        <th class="text-start">Inline</th>
      </tr>
      <tr>
        <td class="font-bold">Taille</td>
        <td>Occupe toute la largeur</td>
        <td>N'occupe que la largeur nécessaire</td>
      </tr>
      <tr>
        <td class="font-bold">Position</td>
        <td>L'un en dessous de l'autre</td>
        <td>Les deux côte-à-côte</td>
      </tr>
      <tr>
        <td class="font-bold">Exemple de balise</td>
        <td><ShowCode raw="<div>" lang="html" :inline="true" /></td>
        <td><ShowCode raw="<span>" lang="html" :inline="true" /></td>
      </tr>
    </table>

    <p>
      Mais en pratique, à quoi servent ces balises ? Voici un tableau avec les
      principales balises à connaître :
    </p>
    <table>
      <tr>
        <th class="text-start">Balise</th>
        <th class="text-start">Inline/block</th>
        <th class="text-start">Description</th>
      </tr>
      <tr>
        <td><ShowCode raw="<div>" lang="html" :inline="true" /></td>
        <td>Block</td>
        <td>
          C'est la balise block "de base", elle permet de séparer les éléments
          pour, par exemple, leurs appliquer une classe CSS.
        </td>
      </tr>
      <tr>
        <td><ShowCode raw="<span>" lang="html" :inline="true" /></td>
        <td>Inline</td>
        <td>
          Équivalent de
          <ShowCode raw="<div>" lang="html" :inline="true" /> mais pour inline.
        </td>
      </tr>
      <tr>
        <td><ShowCode raw="<p>" lang="html" :inline="true" /></td>
        <td>Block</td>
        <td>
          Un paragraphe. Pour insérer un retour à la ligne, utiliser la balise
          <ShowCode raw="<br>" lang="html" :inline="true" />.
        </td>
      </tr>
      <tr>
        <td>
          <ShowCode raw="<h1>" lang="html" :inline="true" />,
          <ShowCode raw="<h2>" lang="html" :inline="true" /> ...
          <ShowCode raw="<h6>" lang="html" :inline="true" />
        </td>
        <td>Block</td>
        <td>
          Les titres et sous-titres du plus important (h1) au moins important
          (h6).
        </td>
      </tr>
      <tr>
        <td><ShowCode raw='<a href="">' lang="html" :inline="true" /></td>
        <td>Inline</td>
        <td>
          <router-link to="/html/hypertexte">Un lien hypertexte</router-link>
        </td>
      </tr>
      <tr>
        <td>
          <ShowCode raw='<img src="" alt="" />' lang="html" :inline="true" />
        </td>
        <td>Block</td>
        <td><router-link to="/html/image">Une image</router-link></td>
      </tr>
      <tr>
        <td><ShowCode raw="<ul>" lang="html" :inline="true" /></td>
        <td>Block</td>
        <td><router-link to="/html/liste">Une liste</router-link></td>
      </tr>
      <tr>
        <td><ShowCode raw="<table>" lang="html" :inline="true" /></td>
        <td>Block</td>
        <td><router-link to="/html/table">Un tableau</router-link></td>
      </tr>
      <tr>
        <td><ShowCode raw="<input>" lang="html" :inline="true" /></td>
        <td>Inline</td>
        <td><router-link to="/html/form">Des champs d'entrée</router-link></td>
      </tr>
    </table>
  </div>
</template>

// angular/epsic-burkhalter-dev/src/app/html-module/components/types-balises/types-balises.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";

declare var Prism: any;

@Component({
  selector: 'app-types-balises',
  templateUrl: './types-balises.component.html',
  styleUrls: ['./types-balises.component.css']
})
export class TypesBalisesComponent implements OnInit {

  public Prism: any = {};

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Les types de balises");
    this.Prism = Prism;
  }

  ngOnInit(): void {
  }

}

<h1>Les types de balises</h1>
<p>Il existe deux types de balises : <strong>block</strong> et <strong>inline</strong>. Voici un petit tableau récapitulatif :</p>
<table class="table">
	<tr>
		<th></th>
		<th>Block</th>
		<th>Inline</th>
	</tr>
	<tr>
		<th>Taille</th>
		<td>Occupe toute la largeur</td>
		<td>N'occupe que la largeur nécessaire</td>
	</tr>
	<tr>
		<th>Position</th>
		<td>L'un en dessous de l'autre</td>
		<td>Les deux côte-à-côte</td>
	</tr>
	<tr>
		<th>Exemple de balise</th>
		<td><app-code class="language-html" inlineCode="<div>" [lang]="Prism.languages.html"></app-code></td>
		<td><app-code class="language-html" inlineCode="<span>" [lang]="Prism.languages.html"></app-code></td>
	</tr>
</table>

<p>Mais en pratique, à quoi servent ces balises ? Voici un tableau avec les principales balises à connaître :</p>
<table class="table">
	<tr>
		<th>Balise</th>
		<th>Inline/block</th>
		<th>Description</th>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode="<div>" [lang]="Prism.languages.html"></app-code></td>
		<td>Block</td>
		<td>C'est la balise block "de base", elle permet de séparer les éléments pour, par exemple, leurs appliquer une classe CSS.</td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode="<span>" [lang]="Prism.languages.html"></app-code></td>
		<td>Inline</td>
		<td>Équivalent de <app-code class="language-html" inlineCode="<div>" [lang]="Prism.languages.html"></app-code> en inline.</td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode="<p>" [lang]="Prism.languages.html"></app-code></td>
		<td>Block</td>
		<td>Un paragraphe. Pour insérer un retour à la ligne, écrire <app-code class="language-html" inlineCode="<br>" [lang]="Prism.languages.html"></app-code>.</td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode="<h1>" [lang]="Prism.languages.html"></app-code>, <app-code class="language-html" inlineCode="<h2>" [lang]="Prism.languages.html"></app-code> ... <app-code class="language-html" inlineCode="<h6>" [lang]="Prism.languages.html"></app-code></td>
		<td>Block</td>
		<td>Les titres et sous-titres du plus important (h1) au moins important (h6).</td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode='<a href="">' [lang]="Prism.languages.html"></app-code></td>
		<td>Inline</td>
		<td><a href="" routerLink="/html/hypertexte">Un lien hypertexte.</a></td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode='<img src="" alt="" />' [lang]="Prism.languages.html"></app-code></td>
		<td>Block</td>
		<td><a href="" routerLink="/html/image">Une image.</a></td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode="<ul>" [lang]="Prism.languages.html"></app-code></td>
		<td>Block</td>
		<td><a href="" routerLink="/html/liste">Une liste.</a></td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode="<table>" [lang]="Prism.languages.html"></app-code></td>
		<td>Block</td>
		<td><a href="" routerLink="/html/table">Un tableau.</a></td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode="<input>" [lang]="Prism.languages.html"></app-code></td>
		<td>Inline</td>
		<td><a href="" routerLink="/html/form">Des champs d'entrée.</a></td>
	</tr>
</table>
