// src/views/html/TypesBalises.vue
<template>
	<div>
		<h1>Les types de balises</h1>
		<p>Il existe deux types de balises : <strong>block</strong> et <strong>inline</strong>. Voici un petit tableau récapitulatif :</p>
		<table class="table">
			<tr>
				<th></th>
				<th>Block</th>
				<th>Inline</th>
			</tr>
			<tr>
				<th>Taille</th>
				<td>Occupe toute la largeur</td>
				<td>N'occupe que la largeur nécessaire</td>
			</tr>
			<tr>
				<th>Position</th>
				<td>L'un en dessous de l'autre</td>
				<td>Les deux côte-à-côte</td>
			</tr>
			<tr>
				<th>Exemple de balise</th>
				<td><ShowCode class="language-html" inlineCode="<div>" lang="html"/></td>
				<td><ShowCode class="language-html" inlineCode="<span>" lang="html"/></td>
			</tr>
		</table>

		<p>Mais en pratique, à quoi servent ces balises ? Voici un tableau avec les principales balises à connaître :</p>
		<table class="table">
			<tr>
				<th>Balise</th>
				<th>Inline/block</th>
				<th>Description</th>
			</tr>
			<tr>
				<td><ShowCode class="language-html" inlineCode="<div>" lang="html"/></td>
				<td>Block</td>
				<td>C'est la balise block "de base", elle permet de séparer les éléments pour, par exemple, leurs appliquer une classe CSS.</td>
			</tr>
			<tr>
				<td><ShowCode class="language-html" inlineCode="<span>" lang="html"/></td>
				<td>Inline</td>
				<td>Équivalent de <ShowCode class="language-html" inlineCode="<div>" lang="html"/> en inline.</td>
			</tr>
			<tr>
				<td><ShowCode class="language-html" inlineCode="<p>" lang="html"/></td>
				<td>Block</td>
				<td>Un paragraphe. Pour insérer un retour à la ligne, écrire <ShowCode class="language-html" inlineCode="<br>" lang="html"/>.</td>
			</tr>
			<tr>
				<td><ShowCode class="language-html" inlineCode="<h1>" lang="html"/>, <ShowCode class="language-html" inlineCode="<h2>" lang="html"/> ... <ShowCode class="language-html" inlineCode="<h6>" lang="html"/></td>
				<td>Block</td>
				<td>Les titres et sous-titres du plus important (h1) au moins important (h6).</td>
			</tr>
			<tr>
				<td><ShowCode class="language-html" inlineCode='<a href="">' lang="html"/></td>
				<td>Inline</td>
				<td><a href="" routerLink="/html/hypertexte">Un lien hypertexte.</a></td>
			</tr>
			<tr>
				<td><ShowCode class="language-html" inlineCode='<img src="" alt="" />' lang="html"/></td>
				<td>Block</td>
				<td><a href="" routerLink="/html/image">Une image.</a></td>
			</tr>
			<tr>
				<td><ShowCode class="language-html" inlineCode="<ul>" lang="html"/></td>
				<td>Block</td>
				<td><a href="" routerLink="/html/liste">Une liste.</a></td>
			</tr>
			<tr>
				<td><ShowCode class="language-html" inlineCode="<table>" lang="html"/></td>
				<td>Block</td>
				<td><a href="" routerLink="/html/table">Un tableau.</a></td>
			</tr>
			<tr>
				<td><ShowCode class="language-html" inlineCode="<input>" lang="html"/></td>
				<td>Inline</td>
				<td><a href="" routerLink="/html/form">Des champs d'entrée.</a></td>
			</tr>
		</table>
	</div>
</template>

<script>
	import ShowCode from '../../components/ShowCode.vue'

	export default {
		name: 'TypesBalises',
		components: {
			ShowCode,
		},
	}
</script>

// angular/epsic-burkhalter-dev/src/app/html-module/components/types-balises/types-balises.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";

declare var Prism: any;

@Component({
  selector: 'app-types-balises',
  templateUrl: './types-balises.component.html',
  styleUrls: ['./types-balises.component.css']
})
export class TypesBalisesComponent implements OnInit {

  public Prism: any = {};

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Les types de balises");
    this.Prism = Prism;
  }

  ngOnInit(): void {
  }

}

<h1>Les types de balises</h1>
<p>Il existe deux types de balises : <strong>block</strong> et <strong>inline</strong>. Voici un petit tableau récapitulatif :</p>
<table class="table">
	<tr>
		<th></th>
		<th>Block</th>
		<th>Inline</th>
	</tr>
	<tr>
		<th>Taille</th>
		<td>Occupe toute la largeur</td>
		<td>N'occupe que la largeur nécessaire</td>
	</tr>
	<tr>
		<th>Position</th>
		<td>L'un en dessous de l'autre</td>
		<td>Les deux côte-à-côte</td>
	</tr>
	<tr>
		<th>Exemple de balise</th>
		<td><app-code class="language-html" inlineCode="<div>" [lang]="Prism.languages.html"></app-code></td>
		<td><app-code class="language-html" inlineCode="<span>" [lang]="Prism.languages.html"></app-code></td>
	</tr>
</table>

<p>Mais en pratique, à quoi servent ces balises ? Voici un tableau avec les principales balises à connaître :</p>
<table class="table">
	<tr>
		<th>Balise</th>
		<th>Inline/block</th>
		<th>Description</th>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode="<div>" [lang]="Prism.languages.html"></app-code></td>
		<td>Block</td>
		<td>C'est la balise block "de base", elle permet de séparer les éléments pour, par exemple, leurs appliquer une classe CSS.</td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode="<span>" [lang]="Prism.languages.html"></app-code></td>
		<td>Inline</td>
		<td>Équivalent de <app-code class="language-html" inlineCode="<div>" [lang]="Prism.languages.html"></app-code> en inline.</td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode="<p>" [lang]="Prism.languages.html"></app-code></td>
		<td>Block</td>
		<td>Un paragraphe. Pour insérer un retour à la ligne, écrire <app-code class="language-html" inlineCode="<br>" [lang]="Prism.languages.html"></app-code>.</td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode="<h1>" [lang]="Prism.languages.html"></app-code>, <app-code class="language-html" inlineCode="<h2>" [lang]="Prism.languages.html"></app-code> ... <app-code class="language-html" inlineCode="<h6>" [lang]="Prism.languages.html"></app-code></td>
		<td>Block</td>
		<td>Les titres et sous-titres du plus important (h1) au moins important (h6).</td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode='<a href="">' [lang]="Prism.languages.html"></app-code></td>
		<td>Inline</td>
		<td><a href="" routerLink="/html/hypertexte">Un lien hypertexte.</a></td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode='<img src="" alt="" />' [lang]="Prism.languages.html"></app-code></td>
		<td>Block</td>
		<td><a href="" routerLink="/html/image">Une image.</a></td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode="<ul>" [lang]="Prism.languages.html"></app-code></td>
		<td>Block</td>
		<td><a href="" routerLink="/html/liste">Une liste.</a></td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode="<table>" [lang]="Prism.languages.html"></app-code></td>
		<td>Block</td>
		<td><a href="" routerLink="/html/table">Un tableau.</a></td>
	</tr>
	<tr>
		<td><app-code class="language-html" inlineCode="<input>" [lang]="Prism.languages.html"></app-code></td>
		<td>Inline</td>
		<td><a href="" routerLink="/html/form">Des champs d'entrée.</a></td>
	</tr>
</table>
