// src/views/java/ConditionsAvancees.vue
<template>
	<div>
		<h1>Les conditions avancées</h1>

		<h3>Le switch</h3>
		<p>Le bloc switch permet de simplifier un code où on utiliserait plusieurs else if à la suite. Exemple :</p>
		<table class="table">
			<thead>
				<tr>
					<th>If else if</th>
					<th>Switch</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>
						<pre class="language-java"><ShowCode file="java/if-else-if-else.java" lang="java"/></pre>
					</td>
					<td>
						<pre class="language-java"><ShowCode file="java/switch.java" lang="java"/></pre>
					</td>
				</tr>
			</tbody>
		</table>
		<p>Le break est très important : il sert à sortir du switch si la condition est remplie. Si vous l'oubliez alors votre switch exécutera la condition plus toutes celles qui se trouve après.</p>
	</div>
</template>

<script>
	import ShowCode from '../../components/ShowCode.vue'

	export default {
		name: 'ConditionsAvancees',
		components: {
			ShowCode,
		},
	}
</script>

// src/app/java-module/components/conditions-avancees/conditions-avancees.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";
import 'prismjs/components/prism-java';

declare var Prism: any;

@Component({
  selector: 'app-conditions-avancees',
  templateUrl: './conditions-avancees.component.html',
  styleUrls: ['./conditions-avancees.component.css']
})
export class ConditionsAvanceesComponent implements OnInit {

  public Prism: any = {};

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Les conditions avancées");
    this.Prism = Prism;
  }

  ngOnInit(): void {
  }

}

<h1>Les conditions avancées</h1>

<h3>Le switch</h3>
<p>Le bloc switch permet de simplifier un code où on utiliserait plusieurs else if à la suite. Exemple :</p>
<table class="table">
	<thead>
		<tr>
			<th>If else if</th>
			<th>Switch</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<pre class="language-java"><app-code file="java/if-else-if-else.java" [lang]="Prism.languages.java"></app-code></pre>
			</td>
			<td>
				<pre class="language-java"><app-code file="java/switch.java" [lang]="Prism.languages.java"></app-code></pre>
			</td>
		</tr>
	</tbody>
</table>
<p>Le break est très important : il sert à sortir du switch si la condition est remplie. Si vous l'oubliez alors votre switch exécutera la condition plus toutes celles qui se trouve après.</p>
