// src/views/access/Access1.vue
<template>
	<div>
		<h1>Ma base de données en Access 1.0</h1>
		<p>Installation d'Access 1.0 sur Windows 3.1</p>
		<iframe width="720" height="480" src="https://www.youtube.com/embed/6fbgRjiuYKs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		<p>Le formulaire F_Personnes de ma bdd dans Access 1.0 :</p>
		<img src="/medias/access/access1_screenshot.png" alt="Capture d'écran" />
		<ul><li><p>La VM est téléchargeable <a href="/medias/access/Windows3.ova">ici</a>.</p></li></ul>
	</div>
</template>

<script>
	export default {
		name: 'Access1',
	}
</script>

// angular/epsic-burkhalter-dev/src/app/access-module/components/access1/access1.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";

@Component({
  selector: 'app-access1',
  templateUrl: './access1.component.html',
  styleUrls: ['./access1.component.css']
})
export class Access1Component implements OnInit {

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Ma base de données en Access 1.0");
  }

  ngOnInit(): void {
  }

}

<h1>Ma base de données en Access 1.0</h1>
<p>Installation d'Access 1.0 sur Windows 3.1</p>
<iframe width="720" height="480" src="https://www.youtube.com/embed/6fbgRjiuYKs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<p>Le formulaire F_Personnes de ma bdd dans Access 1.0 :</p>
<img src="/medias/access/access1_screenshot.png" alt="Capture d'écran" />
<ul><li><p>La VM est téléchargeable <a href="/medias/access/Windows3.ova">ici</a>.</p></li></ul>
