// src/views/bin/BinHex.vue
<template>
	<div>
		<h1>Conversion binaire - hexa</h1>
		<table>
			<tr><th>Décimal</th><th>Hexadécimal</th><th>Binaire</th></tr>
			<tr><td>0</td><td>0</td><td>0000</td></tr>
			<tr><td>1</td><td>1</td><td>0001</td></tr>
			<tr><td>2</td><td>2</td><td>0010</td></tr>
			<tr><td>3</td><td>3</td><td>0011</td></tr>
			<tr><td>4</td><td>4</td><td>0100</td></tr>
			<tr><td>5</td><td>5</td><td>0101</td></tr>
			<tr><td>6</td><td>6</td><td>0110</td></tr>
			<tr><td>7</td><td>7</td><td>0111</td></tr>
			<tr><td>8</td><td>8</td><td>1000</td></tr>
			<tr><td>9</td><td>9</td><td>1001</td></tr>
			<tr><td>10</td><td>A</td><td>1010</td></tr>
			<tr><td>11</td><td>B</td><td>1011</td></tr>
			<tr><td>12</td><td>C</td><td>1100</td></tr>
			<tr><td>13</td><td>D</td><td>1101</td></tr>
			<tr><td>14</td><td>E</td><td>1110</td></tr>
			<tr><td>15</td><td>F</td><td>1111</td></tr>
		</table>
		<hr>
		<p>Un symbole hexadécimal équivaut à 4 bits. On peut donc directement regrouper les bits par groupe de 4 et les remplacer selon le tableau.</p>
		<p>Exemple : 10010111010<sub>2</sub> = 4BA<sub>16</sub></p>
		<table style="text-align: center;">
			<tr><td style="border-right: 1px solid black;">4</td><td style="border-right: 1px solid black;">B</td><td>A</td></tr>
			<tr><td style="border-right: 1px solid black;">100</td><td style="border-right: 1px solid black;">1011</td><td>1010</td></tr>
		</table>
	</div>
</template>

<script>
	export default {
		name: 'BinHex',
	}
</script>

// angular/epsic-burkhalter-dev/src/app/bin-module/components/bin-hex/bin-hex.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from "@angular/platform-browser";

@Component({
  selector: 'app-bin-hex',
  templateUrl: './bin-hex.component.html',
  styleUrls: ['./bin-hex.component.css']
})
export class BinHexComponent implements OnInit {

  constructor(private _titleService: Title) {
    this._titleService.setTitle("Conversion binaire - hexa");
  }

  ngOnInit(): void {
  }

}

<h1>Conversion binaire - hexa</h1>
<table>
	<tr><th>Décimal</th><th>Hexadécimal</th><th>Binaire</th></tr>
	<tr><td>0</td><td>0</td><td>0000</td></tr>
	<tr><td>1</td><td>1</td><td>0001</td></tr>
	<tr><td>2</td><td>2</td><td>0010</td></tr>
	<tr><td>3</td><td>3</td><td>0011</td></tr>
	<tr><td>4</td><td>4</td><td>0100</td></tr>
	<tr><td>5</td><td>5</td><td>0101</td></tr>
	<tr><td>6</td><td>6</td><td>0110</td></tr>
	<tr><td>7</td><td>7</td><td>0111</td></tr>
	<tr><td>8</td><td>8</td><td>1000</td></tr>
	<tr><td>9</td><td>9</td><td>1001</td></tr>
	<tr><td>10</td><td>A</td><td>1010</td></tr>
	<tr><td>11</td><td>B</td><td>1011</td></tr>
	<tr><td>12</td><td>C</td><td>1100</td></tr>
	<tr><td>13</td><td>D</td><td>1101</td></tr>
	<tr><td>14</td><td>E</td><td>1110</td></tr>
	<tr><td>15</td><td>F</td><td>1111</td></tr>
</table>
<hr>
<p>Un symbole hexadécimal équivaut à 4 bits. On peut donc directement regrouper les bits par groupe de 4 et les remplacer selon le tableau.</p>
<p>Exemple : 10010111010<sub>2</sub> = 4BA<sub>16</sub></p>
<table style="text-align: center;">
	<tr><td style="border-right: 1px solid black;">4</td><td style="border-right: 1px solid black;">B</td><td>A</td></tr>
	<tr><td style="border-right: 1px solid black;">100</td><td style="border-right: 1px solid black;">1011</td><td>1010</td></tr>
</table>
